objects/CleanQuote__c.object
<CustomObject>
    <description>Object for CleanQuote to write to, that then can write to Lead Objects</description>
    <fields>
        <fullName>CQ_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Lead that is Associated with CQ</inlineHelpText>
        <label>CQ Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>CleanQuotes</relationshipLabel>
        <relationshipName>CleanQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CleanQuote</label>
    <nameField>
        <displayFormat>CQ-{YYYY}{MM}{0000}</displayFormat>
        <label>CleanQuote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CleanQuotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentTriggerHandler.cls
public class AttachmentTriggerHandler  {

    public static void onAfterInsert(List<Attachment> listOfAttachment) {
        SObjectType customMetaType = Schema.getGlobalDescribe().get('CleanQuote__c');
        String keyPrefix = customMetaType.getDescribe().getKeyPrefix();
        Set<String> setOFCleanQuotes = new Set<String>();
        for(Attachment itemAtt : listOfAttachment) {
            if(String.valueOf(itemAtt.ParentId).startsWith(keyPrefix)) {
                setOFCleanQuotes.add(itemAtt.ParentId);
            }
        }
        List<Attachment> listToInsert = moveAttachmentsToLead(setOFCleanQuotes);
        if(listToInsert.size() > 0) {
            insert listToInsert;
        }

    }

    private static List<Attachment> moveAttachmentsToLead(Set<String> setOFCleanQuotes) {
        System.debug(setOFCleanQuotes);
        Map<Id, Id> mapofQuoteLead = new Map<Id,Id>();
        for(CleanQuote__c itemQuote : [SELECt Id, CQ_Lead__c FROM CleanQuote__c WHERE Id IN :setOFCleanQuotes]) {
            mapofQuoteLead.put(itemQuote.Id, itemQuote.CQ_Lead__c);
        }
        System.debug(mapofQuoteLead);
        Set<String> setOfLeadAttachment = new Set<String>();
        for(Attachment itemAtt : [SELECT Id, Name FROM Attachment WHERE ParentId = :mapofQuoteLead.values()]) {
            setOfLeadAttachment.add(itemAtt.Name);
        }
        List<Attachment> listOfAttachment = new List<Attachment>();
        for(Attachment itemAtt : [SELECT Id, BodyLength, Body, ParentId, ContentType, Description, IsPrivate, IsPartnerShared, Name FROM Attachment WHERE ParentId = :mapofQuoteLead.keySet()]) {
            if(!setOfLeadAttachment.contains(itemAtt.Name)){
                Attachment attInsert = itemAtt.clone(false,false,false,false);
                attInsert.ParentId = mapofQuoteLead.get(itemAtt.ParentId);
                listOfAttachment.add(attInsert);
            }
        }
        return listOfAttachment;
    }
}