objects/Exception_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Exception Criteria</relationshipLabel>
        <relationshipName>Exception_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Exception Criteria</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Exception Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lien__c.object
<CustomObject>
    <description>Describes the outstanding debt on the field.</description>
    <fields>
        <fullName>Amortization_at_Origination_years__c</fullName>
        <label>Amortization at Origination- years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Debt_Service__c</fullName>
        <label>Annual Debt Service</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cross_Collateralized_Defaulted__c</fullName>
        <label>Cross Collateralized-Defaulted</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cross-Collateralized</fullName>
                </value>
                <value>
                    <fullName>Cross-Defaulted</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Balance_as_of_Date__c</fullName>
        <label>Current Balance as of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Balance__c</fullName>
        <label>Current Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debt_Position__c</fullName>
        <inlineHelpText>What is the position of this lender in the loss position?</inlineHelpText>
        <label>Debt Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st</fullName>
                </value>
                <value>
                    <fullName>2nd</fullName>
                </value>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>4th</fullName>
                </value>
                <value>
                    <fullName>5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <label>Interest Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Float</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <inlineHelpText>The interest rate on this lien.</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lender_Acknowledgement__c</fullName>
        <inlineHelpText>Date the Lender has acknowledged that a PACE lien is being place on the property.</inlineHelpText>
        <label>Lender Acknowledgement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lender_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The is the name of the lender contact.  Please fill out the email and phone</inlineHelpText>
        <label>Lender Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Liens</relationshipLabel>
        <relationshipName>Liens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lender_Type__c</fullName>
        <description>Type of Lender</description>
        <inlineHelpText>Type of Lender</inlineHelpText>
        <label>Lender Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>CMBS</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Mezzanine</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lien_LTV_As_Complete__c</fullName>
        <formula>Current_Loan_Balance__c / Opportunity__r.Appraised_Property_Value_As_Complete__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lien LTV As-Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lien_LTV_As_Is__c</fullName>
        <formula>Current_Loan_Balance__c / Opportunity__r.Property_Market_Value_Est__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lien LTV As-Is</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <label>Loan Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Months_Interest_only__c</fullName>
        <inlineHelpText>Enter # of mos, or &quot;0&quot; if N/A</inlineHelpText>
        <label>Months Interest only</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The name of the bank or lender.</inlineHelpText>
        <label>Mortgage Lender</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Liens</relationshipLabel>
        <relationshipName>Liens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Any Notes on this lien.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Liens</relationshipLabel>
        <relationshipName>Opportunity_Liens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Origination_Date__c</fullName>
        <inlineHelpText>This is the origination date of lien</inlineHelpText>
        <label>Origination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Special_Servicer_File__c</fullName>
        <label>Special Servicer File #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Servicer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Servicer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Liens (Special Servicer)</relationshipLabel>
        <relationshipName>Liens1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Lein__c</fullName>
        <label>Type of Lien</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Bridge</fullName>
                </value>
                <value>
                    <fullName>Construction Loan</fullName>
                </value>
                <value>
                    <fullName>Mini-Perm</fullName>
                </value>
                <value>
                    <fullName>Secured Debt</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Lender__c</fullName>
        <inlineHelpText>What kind of lender is this?</inlineHelpText>
        <label>Type of Lender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>CMBS</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Mezzanine</fullName>
                </value>
                <value>
                    <fullName>Municipal Bond</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lien</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Lien Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>Estimated loan coupon (not final)</description>
        <label>Interest Rate</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <inlineHelpText>This is the Loan Number of the 1st Mortgage</inlineHelpText>
        <label>Loan Number (1st)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Mortgage lender on the transaction (direct or servicer)
Please select &quot;No Lender&quot; in case of no lender. You can find this placeholder account through the lookup field.</description>
        <inlineHelpText>Use the lookup field to the right to select or add a new mortgage lender.</inlineHelpText>
        <label>Mortgage Lender (1st)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <description>This is to capture tenant information.</description>
    <fields>
        <fullName>Notes_and_Comments__c</fullName>
        <inlineHelpText>Notes on this tenant.</inlineHelpText>
        <label>Notes and Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Opportunity_Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Placeholder_Tenant__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tenant represents a rollup of multiple vacant or filled spaces.</inlineHelpText>
        <label>Placeholder Tenant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TenantBySqFtSortOder__c</fullName>
        <inlineHelpText>This is updated via a trigger and maintains the sort order of the Tenants in an opportunity.</inlineHelpText>
        <label>TenantBySqFtSortOder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tenant_Income__c</fullName>
        <inlineHelpText>This is the total amount of income paid by all tenants in the Property.</inlineHelpText>
        <label>Tenant Income - Annual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tenant_Lease_Type__c</fullName>
        <inlineHelpText>What type of Lease is this tenant under?</inlineHelpText>
        <label>Tenant Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NNN</fullName>
                </value>
                <value>
                    <fullName>Modified Gross</fullName>
                </value>
                <value>
                    <fullName>Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenant_Square_Foot__c</fullName>
        <label>Tenant Square Foot</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OppCAPTemplateCntr.cls
public class OppCAPTemplateCntr  {
    public Opportunity oppItem{get;set;}
    public Exception_Criteria__c exCriteria{get;set;}
    public Account accToGet{get;set;}

    public OppCAPTemplateCntr(ApexPages.StandardController stdController) {
        this.oppItem = (Opportunity)stdController.getRecord();
         oppItem = (Opportunity)ApexHelperUtility.queryAllFieldsObjectOPP('Opportunity', oppItem.Id);
         exCriteria = queryExCriteria(oppItem);
         accToGet = queryOppAcount();
    }

    public List<Schema.FieldSetMember> getFieldsSummary() {
       List<Schema.FieldSetMember> listToReturn = new List<Schema.FieldSetMember>();
       listToReturn = SObjectType.Opportunity.FieldSets.Summary.getFields();
       return listToReturn;
    }

    public List<Schema.FieldSetMember> getFieldsAnalysis() {
       List<Schema.FieldSetMember> listToReturn = new List<Schema.FieldSetMember>();
       listToReturn = SObjectType.Opportunity.FieldSets.Analysis.getFields();
       return listToReturn;
    }

    public List<Schema.FieldSetMember> getFieldsCollateral() {
       List<Schema.FieldSetMember> listToReturn = new List<Schema.FieldSetMember>();
       listToReturn = SObjectType.Opportunity.FieldSets.Collateral.getFields();
       return listToReturn;
    }

    public Exception_Criteria__c queryExCriteria(Opportunity inputOpp) {
        Exception_Criteria__c exCriteriaQueried;
        if(ApexHelperUtility.queryAllFieldsObjectWithRelation('Exception_Criteria__c', inputOpp.Id, new List<String>()) != null){
            exCriteriaQueried = (Exception_Criteria__c)ApexHelperUtility.queryAllFieldsObjectWithRelation('Exception_Criteria__c', inputOpp.Id, new List<String>());
        } else {
            exCriteriaQueried = new Exception_Criteria__c();
        }
        return exCriteriaQueried;
    }

    public PageReference save() {
        upsert oppItem;
        upsert exCriteria;
        return new PageReference('/'+oppItem.Id);
    }

    public PageReference cancel() {
        return new PageReference('/'+oppItem.Id);
    }

    public List<Tenant__c> getTenants() {
        return [SELECT Id, Name, Notes_and_Comments__c, Placeholder_Tenant__c, TenantBySqFtSortOder__c, Tenant_Income__c, Tenant_Lease_Type__c, Tenant_Square_Foot__c FROM Tenant__c WHERE Opportunity__c = :oppItem.Id];
    }

    public List<Lien__c> getLien() {
        return [SELECT Amortization_at_Origination_years__c,Annual_Debt_Service__c,ConnectionReceivedId,ConnectionSentId,CreatedById,CreatedDate,Cross_Collateralized_Defaulted__c,Current_Balance_as_of_Date__c,Current_Loan_Balance__c,Debt_Position__c,Id,Interest_Rate_Type__c,Interest_Rate__c,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Lender_Acknowledgement__c,Lender_Contact__c,Lender_Type__c,Lien_LTV_As_Complete__c,Lien_LTV_As_Is__c,Loan_Number__c,Maturity_Date__c,Months_Interest_only__c,Mortgage_Lender__c,Name,Notes__c,Opportunity__c,Origination_Date__c,Special_Servicer_File__c,Special_Servicer__c,SystemModstamp,Type_of_Lein__c,Type_of_Lender__c FROM Lien__c WHERE Opportunity__c = :oppItem.Id];
    }

    public Account queryOppAcount() {
        List<Account> listOfAccounts = new List<Account>([SELECT Id, Name, Entity_Type__c, Entity_Status__c, Entity_Date_Formed__c, Entity_State__c, Entity_Tax_ID__c, Financial_Crime__c, Public_Records_Search_Date__c, Foreclosure_Short_Sale_Deed_in_Lieu__c, Bankruptcy__c, Litigation__c, Sponsor_Name__c, Entity_Filling__c, Tenants_in_Common__c, Public_Record_Search_Notes__c FROM Account WHERE Id = :oppItem.AccountId]);
        if(listOfAccounts.size() > 0) {
            return listOfAccounts[0];
        } else {
            return null;
        }
    }

}