objects/IntegrationHistory__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <label>Lead Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mapping__c</fullName>
        <label>Mapping</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integration History</label>
    <nameField>
        <displayFormat>IH-{0000}</displayFormat>
        <label>Integration History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IntegrationHistoryService.cls
@RestResource(urlMapping='/integrationHistory/*')
global class IntegrationHistoryService {
	
	@HttpPost
    global  static List<IntegrationHistory__c> getIntegrationHistoryRecord(Id leadId) {
		List<IntegrationHistory__c> intHistory;
        try{
        	intHistory = new List<IntegrationHistory__c>([SELECT Mapping__c FROM IntegrationHistory__c WHERE LeadId__c = :leadId]);
        } catch(Exception ex) {
            return null;
        }
        return intHistory;
    }
    
    @HttpGet
    global static List<IntegrationHistory__c> convertLead() {
        String leadId = RestContext.request.params.get('leadId');
        SavePoint sp = Database.setSavepoint();
        try{
        	if(!String.isEmpty(leadId)) {
                LeadConvertClass convertLeadClass = new LeadConvertClass();
                if(!Test.isRunningTest()){
            	    convertLeadClass.convertLead((Lead)ApexHelperUtility.queryAllFieldsObject('Lead', leadId));
                }
        	}
            List<IntegrationHistory__c> intHistory = new List<IntegrationHistory__c>([SELECT Mapping__c FROM IntegrationHistory__c WHERE LeadId__c = :leadId]);
            return intHistory;
        }catch(Exception ex) {
            return null;
        }
    }  
}