objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Backfill</fullName>
                </value>
                <value>
                    <fullName>No Legislation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramAdminName__c</fullName>
        <label>Program Admin Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recommendation__c</fullName>
        <label>Recommendation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Approval</fullName>
                </value>
                <value>
                    <fullName>Conditional Approval</fullName>
                </value>
                <value>
                    <fullName>Approved with Reservations</fullName>
                </value>
                <value>
                    <fullName>Basic Screen</fullName>
                </value>
                <value>
                    <fullName>Not Approved/Screened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnderwritingStatus__c</fullName>
        <label>Underwriting Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectsPageTest.cls
@isTest
public class ProjectsPageTest  {

    public static testmethod void testProject() {
        Program__c programToInsert = new Program__c();
            programToInsert.Name = 'Test';
            programToInsert.ProgramAdminName__c = 'Test';
            programToInsert.State__c = 'CA';
            programToInsert.UnderwritingStatus__c = 'Complete';
            programToInsert.Recommendation__c = 'Full Approval';
            programToInsert.Priority__c = 'Backfill';
        insert programToInsert;
        PageReference pageRef = Page.ProjectEgnytePage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(programToInsert.Id));
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new EgnyteHttpCalloutImpl());
            ApexPages.StandardController sc = new ApexPages.StandardController(programToInsert);
            ProjectsPage egnyteIframe = new ProjectsPage(sc);
            System.assert(egnyteIframe.iframeRenderer);
        Test.stopTest();
    }
}