src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Status__c</fullName>
        <description>The current status of the client.</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <inlineHelpText>The high level way in which this contact was introduced to CleanFund.  CF Sub Lead source captures the specific way we were introduced.</inlineHelpText>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.Street_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub-Lead Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <formula>Account.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Partner_Main_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Partner Main Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel Partner associated with Opportunity</description>
        <label>Channel Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Channel Partner Entity)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Partner_Main_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Contact at Channel Partner associated with Opportunity</description>
        <label>Channel Partner Main Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Entry_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date project identified. Please note this may be earlier than entry into CleanFund&apos;s pipeline portal.</description>
        <inlineHelpText>Date project identified. Please note this may be earlier than entry into CleanFund&apos;s pipeline portal.</inlineHelpText>
        <label>Project Identified Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>Estimated loan term (not final)</description>
        <inlineHelpText>Desired length of financing term, expressed in years</inlineHelpText>
        <label>Financing Term</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Identifier__c</fullName>
        <defaultValue>$User.CompanyName</defaultValue>
        <label>PACEPartner Identifier</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_City__c</fullName>
        <label>City (PACEPartner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_State__c</fullName>
        <label>State (PACEPartner)</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_Street_Address__c</fullName>
        <label>Street Address (PACEPartner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_Zip_Code__c</fullName>
        <label>Zip Code (PACEPartner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the PACEPartner primary contact.</inlineHelpText>
        <label>Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant Name)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Project_Number__c</fullName>
        <inlineHelpText>PACE Partner&apos;s internal project reference number or ID.</inlineHelpText>
        <label>PACEPartner Project Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <description>Sub-lead source for Opportunity to provide additional granularity</description>
        <label>Sub Lead Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>CleanFund Underwriter Assigned by CleanFund)</inlineHelpText>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validated_by_CF__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes a deal that has been validated by a CleanFund employee.</description>
        <label>Validated by CF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>Zip Code property is located in</inlineHelpText>
        <label>Zip Code - Property</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Account_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>Industry Association</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/CF_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor on Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search (Outbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry (Inbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
        <isActive>false</isActive>
        <label>Website Inquiry</label>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
        <isActive>false</isActive>
        <label>Web Search</label>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
        <isActive>false</isActive>
        <label>UNKNOWN</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
        <isActive>false</isActive>
        <label>Journal</label>
    </customValue>
    <masterLabel>CF Lead Source</masterLabel>
</GlobalValueSet>

src/globalValueSets/Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CleanQuote</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

classes/CustomOpportunityController.cls
public without sharing class CustomOpportunityController
{

 public String  opportunityName {get; set;}
 public String  ppProjectNumber {get; set;}
 public String  accountName {get; set;}
 public String  companyName {get; set;}
 public String  mainContact {get; set;}
 public String  pp_project_number {get; set;}
 
 public CustomOpportunityController () {}
 
 public PageReference createOpportunity() 
 {
    Opportunity opportunity = new Opportunity();
        
    try {
        system.debug('Oppurtunity Name : ' + opportunityName);
        system.debug('Pace Project Number : ' + ppProjectNumber);
        system.debug('Account Name : ' + accountName);

        Id UserId = UserInfo.getUserId();
        Id companyId;
        Id contactId;
        Id opportunityId;
        String BaseURL;
        String refUrl;

        String Email;
        String Phone;
        String Street_Address;
        String City;
        String State;
        String ZipCode;

        system.debug('Current logged in User ID : ' + UserId);

        if (UserId != null) {

            List<User> userlst = [
                    SELECT Name, Account.Id, Account.Name, Contact.Id,
                            Contact.Email, Contact.Phone,
                            Account.Street_Address__c, Account.City__c,
                            Account.State__c, Account.zip_code__c
                    FROM User
                    WHERE Id = :UserId
                    LIMIT 1
            ];

            User user;

            if (userlst.size() > 0) {
                user = userlst[0];
                companyName = user.Account.Name;
                companyId = user.Account.Id;
                contactId = user.Contact.Id;

                mainContact = user.Name;
                Email = user.Contact.Email;
                Phone = user.Contact.Phone;
                Street_Address = user.Account.Street_Address__c;
                City = user.Account.City__c;
                State = user.Account.State__c;
                ZipCode = user.Account.zip_code__c;

                system.debug('Users - company name : ' + companyName);
                system.debug('Users - main contact : ' + mainContact);
                system.debug('Users - companyId    : ' + companyId);
                system.debug('Users - contactId    : ' + contactId);

            } else {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'User Company Name not found'));
            }
        }

        Account account;
        List<Account> accountlst = [
                SELECT Id, Name
                FROM Account
                WHERE Name = :accountName
                LIMIT 1
        ];

        if (accountlst.size() > 0) {
            account = accountlst[0];
            system.debug('Successfully account retrieved ' + account.Name + ' with Id:' + account.Id);
        } else {
            account = new Account();
            account.Name = accountName;
            account.Client_Status__c = 'Pre-Contact';
            account.Sub_Lead_Source__c ='test';
            account.CF_Lead_Source__c ='Other';
            account.Account_Type__c = 'N/A';
            insert account;
            system.debug('Successfully account created ' + account.Name + ' with Id:' + account.Id);

            accountlst = [
                    SELECT Id
                    FROM Account
                    WHERE Name = :accountName
                    LIMIT 1
            ];

            if (accountlst.size() > 0) {
                account = accountlst[0];
            }
        }
        opportunity.accountId = account.id;
        opportunity.Name = opportunityName;
        opportunity.StageName = 'Pre-Qualified Lead';
        opportunity.Loan_Term__c = 20;
        opportunity.PACEPartner_Project_Number__c = ppProjectNumber;
        opportunity.Initial_Entry_Date__c = system.today();
        opportunity.CloseDate = system.today().addDays(90);
        opportunity.LeadSource = 'Channel Partner';
        opportunity.Channel_Partner_Entity__c = companyId;
        opportunity.Channel_Partner_Main_Contact__c = contactId;
        opportunity.Validated_by_CF__c = false;
        opportunity.Sub_Lead_Source__c = companyName;
        opportunity.PACEPartner_Mailing_City__c = City;
        opportunity.PACEPartner_Email__c = Email;
        opportunity.PACEPartner_Name__c = contactId;
        opportunity.PACEPartner_Phone__c = Phone;
        opportunity.PACEPartner_Mailing_State__c = State;
        opportunity.PACEPartner_Mailing_Street_Address__c = Street_Address;
        opportunity.PACEPartner_Mailing_Zip_Code__c = ZipCode;
      /* Renee Pifer is default transaction manager */
        opportunity.Transaction_Manager__c = '005j000000CAYj4AAH';
        /* Set the identifier to the PARTNER */
        opportunity.PACEPartner_Identifier__c = opportunity.Channel_Partner_Entity__c;

        list<OpportunityShare> lstOpportunityShare = [Select UserOrGroupId, OpportunityId, OpportunityAccessLevel,Id, RowCause From OpportunityShare];

        system.debug('------------ list all the current shares1 -----------' + lstOpportunityShare[0]);


        /* Set up the default Opportunity Owner */

      /* Solar City - Brandon is Owner*/
        if (opportunity.Channel_Partner_Entity__c == '001j000000YSGyd') {
           opportunity.OwnerID = '005j000000CAPu5';
        } /* Solar Engine - Brandon is Owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000khX8m') {
            opportunity.OwnerID = '005j000000CAPu5';
        } /* View Glass - Chris Robbins is owner*/
        else if (opportunity.Channel_Partner_Entity__c == '001j000000Sd0sR') {
            opportunity.OwnerID = '005j000000BcK6J';
        } /* Minerva - Chris Robbins is owner*/
        else if (opportunity.Channel_Partner_Entity__c == '001j000000khGar') {
            opportunity.OwnerID = '005j000000BcK6J';
        }/* Pace Houston - Joshua is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000WDrWj') {
            opportunity.OwnerID = '005j000000BcK6x';
        } /* NRG Answers - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000VZFSa') {
            opportunity.OwnerID = '005j000000BcK6J';
        } /* Stok - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000j9ZVB') {
            opportunity.OwnerID = '005j000000BcK6J';
        }/* CBJ - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000Wuxl0') {
            opportunity.OwnerID = '005j000000BcK6J';
        }/* Integral - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000Sd0ol') {
            opportunity.OwnerID = '005j000000BcK6J';
        }/* Comfort Systems - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000Vayxp') {
            opportunity.OwnerID = '005j000000BcK6J';
        } /* PACE Sage - Joshua is the Opportunity Owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000WZrTL') {
            opportunity.OwnerID = '005j000000BcK6x';
        } /* Platinum Solar - Brandon is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000re5Eq') {
            opportunity.OwnerID = '005j000000CAPu5';
        } /* Frank Owens - Chris is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000l9tk9') {
            opportunity.OwnerID = '005j000000BcK6J';
        } /* Resolve Finance - Joshua is the owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000kfQMd') {
            opportunity.OwnerID = '005j000000BcK6x';
        } /* Onital Energy - Joshua is owner */
        else if (opportunity.Channel_Partner_Entity__c == '001j000000ul7bA') {
            opportunity.OwnerID = '005j000000BcK6x';
        } /* Donovan Energe - Joe is owner */
        else if (opportunity.Channel_Partner_Entity__c == '0010a00001A9HQA') {
            opportunity.OwnerID = '005j000000BcK6d';
        }
        /* Chris Robbins is default owner,  PACEPartner Tier 2 Partner Manager is default share */
        else {
           opportunity.OwnerID = '005j000000BcK6J';
        }

        system.debug('Just before opportunity insertion ');
        insert opportunity;
        opportunityId = opportunity.Id;
        system.debug('Just after opportunity insertion ');
        BaseURL = ApexPages.currentPage().getHeaders().get('Host');
        system.debug('Just after getting BaseURL ' + BaseURL);
        system.debug('Just after getting Opportunity ID : ' + opportunityId);
        refUrl = '/' + opportunityId ;
        system.debug('Just after getting refUrl : ' + refUrl);

        system.debug('------------ opportunity  -----------' + opportunity);
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Opportunity created successfully'));

        PageReference ref = new PageReference(refUrl);
        ref.setRedirect(true);


        system.debug('------------ opportunity owneer  -----------' + opportunity.OwnerID);

        system.debug('------------ opportunity owneer  -----------' +ref);


        return ref;
  } 
  catch (DMLException e) 
  {
      ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error while creating Opportunity'));
      return null;
  } 
  finally 
  {
  }
    
    return null;
 }

}