src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Next_Step__c</fullName>
        <label>Next Step</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AccountTypeNew__c</fullName>
        <description>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</description>
        <inlineHelpText>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Step_Tickler__c</fullName>
        <label>Next Step Tickler</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Owner_Main_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Owner Main Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Property Owner Main Contact)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Lead Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Identified</fullName>
                </value>
                <value>
                    <fullName>Pre-Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Dead/Lost</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                    <isActive>false</isActive>
                    <label>Quoted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GlobalAccType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
        <label>Lender</label>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>City</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>County</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
        <default>true</default>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Third party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>GlobalAccType</masterLabel>
</GlobalValueSet>

src/classes/LTN_CreateRecordCntr.cls
public class LTN_CreateRecordCntr {
    public static Map<Id, String> recordtypemap {get;set;}
    
	@AuraEnabled
    public static Id saveContactCntr(Contact inputContact) {
        inputContact.AccountId = String.valueOf(inputContact.AccountId);
        System.debug(inputContact);
        insert inputContact;
        return inputContact.Id;
    }
    
    @AuraEnabled
    public static Id saveLeadCntr(Lead inputLead) {
        System.debug(inputLead);
        Account accToQuery = [SELECT Id, Name FROM Account WHERE Id = :inputLead.Account_Name__c];
        Contact contactToQuery = [SELECT id, FirstName, LastName FROM Contact WHERE Id = :inputLead.Property_Owner_Main_Contact__c];
        inputLead.Company = accToQuery.Name;
        inputLead.FirstName = contactToQuery.FirstName;
        inputLead.LastName = contactToQuery.LastName;
        insert inputLead;
        Task taskToInsert = new Task();
            taskToInsert.Subject = inputLead.Next_Step__c;
            taskToInsert.ActivityDate = inputLead.Next_Step_Tickler__c;
            taskToInsert.WhoId = inputLead.Id;
            taskToInsert.OwnerId = UserInfo.getUserId();
        insert taskToInsert;
        return inputLead.Id;
    }
    
    @AuraEnabled
    public static Id saveAccountCntr(Account inputAccount) {
        insert inputAccount;
        return inputAccount.Id;
    }
    
    @AuraEnabled        
    public static List<String> fetchRecordTypeValues(){
        List<RecordType> recordtypes = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Account' ORDER BY Name DESC]; 
        recordtypemap = new Map<Id, String>();
        for(RecordType rt : recordtypes){
            recordtypemap.put(rt.Id, rt.Name);
        }        
        return recordtypemap.values();
    }
    
    @AuraEnabled
    public static Id getRecTypeId(String recordTypeLabel){
        Id recid = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeLabel).getRecordTypeId();        
        return recid;
    }
    
    private static Contact getContact(){
        Contact contactToReturn = null;
        List<Contact> listOfContacts = new List<Contact>([SELECT Id, FirstName, LastName FROM Contact WHERE Name = 'Unknown Owner']);
        if(listOfContacts.size() >0) {
            contactToReturn = listOfContacts[0];
        }
        return contactToReturn;
    }
    
    @AuraEnabled
    public static Account getAccount(){
        Account accountToReturn = null;
        List<Account> listOfAccounts = new List<Account>([SELECT Id, Name FROM Account WHERE Name = 'Uncategorized']);
        if(listOfAccounts.size() >0) {
            accountToReturn = listOfAccounts[0];
        }
        return accountToReturn;
    }
    
    @AuraEnabled
    public static Id saveLeadCntrDefault(Lead inputLead) {
        System.debug(inputLead);
        Account accToQuery = getAccount();
        Contact conToQuery = getContact();
        if(conToQuery != null && accToQuery!= null){
        	inputLead.Account_Name__c = accToQuery.Id;
        	inputLead.Property_Owner_Main_Contact__c = conToQuery.Id;
        	inputLead.Company = accToQuery.Name;
        	inputLead.FirstName = conToQuery.FirstName;
        	inputLead.LastName = conToQuery.LastName;
            inputLead.AccountTypeNew__c = 'Owner';
            inputLead.Stage__c = 'Pre-Qualified Lead';
        }
        insert inputLead;
        Task taskToInsert = new Task();
            taskToInsert.Subject = inputLead.Next_Step__c;
            taskToInsert.ActivityDate = inputLead.Next_Step_Tickler__c;
            taskToInsert.WhoId = inputLead.Id;
            taskToInsert.OwnerId = UserInfo.getUserId();
        insert taskToInsert;
        System.debug(inputLead);
        return inputLead.Id;
    }


}