src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <inlineHelpText>The high level way in which this contact was introduced to CleanFund.  CF Sub Lead source captures the specific way we were introduced.</inlineHelpText>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub-Lead Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/CF_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor on Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search (Outbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry (Inbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
        <isActive>false</isActive>
        <label>Website Inquiry</label>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
        <isActive>false</isActive>
        <label>Web Search</label>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
        <isActive>false</isActive>
        <label>UNKNOWN</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
        <isActive>false</isActive>
        <label>Journal</label>
    </customValue>
    <masterLabel>CF Lead Source</masterLabel>
</GlobalValueSet>

src/globalValueSets/Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CleanQuote</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

src/classes/AccountsLeadSource.cls
public class AccountsLeadSource {
    
    public void copyLeadSource (){
        List<Account> existingAccounts = new List<Account>([Select id, Name,Description,CF_Lead_Source__c, Sub_Lead_Source__c FROM Account]);
        List<Contact> exisitngContacts = new List<Contact>([SELECT id, name,AccountID, CF_Lead_Source__c, Sub_Lead_Source__c FROM Contact where AccountID in :existingAccounts Order BY CreatedDate]);
        // System.debug(existingAccounts);
        List<Account> result = new List<Account>();
        for(Account acc :existingAccounts){
            for(Contact cont :exisitngContacts){
                if(cont.AccountID == acc.Id && acc.CF_Lead_Source__c == null && acc.Sub_Lead_Source__c == null && acc.Description == null){
                    acc.CF_Lead_Source__c = cont.CF_Lead_Source__c;
                    acc.Sub_Lead_Source__c = cont.Sub_Lead_Source__c;
                    If(acc.Description == null){
                        acc.Description = ' ';
                    }else (acc.Description += ' ');
                    result.add(acc);
                }
            }
            
        }
       // updateAccBatch UAB = new updateAccBatch();
       // System.executeBatch(UAB);
    }
}