src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Status__c</fullName>
        <description>The current status of the client.</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <inlineHelpText>If this account record represents a property owner, or some entity connected to an opportunity.  Then the entity information should be filled in.</inlineHelpText>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <inlineHelpText>The high level way in which this contact was introduced to CleanFund.  CF Sub Lead source captures the specific way we were introduced.</inlineHelpText>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Can_contact_with_marketing_materials__c</fullName>
        <inlineHelpText>Can CleanFund reach out to this person with marketing collateral?</inlineHelpText>
        <label>Can contact with marketing materials?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.Street_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub-Lead Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <formula>Account.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/CF_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor on Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search (Outbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry (Inbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
        <isActive>false</isActive>
        <label>Website Inquiry</label>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
        <isActive>false</isActive>
        <label>Web Search</label>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
        <isActive>false</isActive>
        <label>UNKNOWN</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
        <isActive>false</isActive>
        <label>Journal</label>
    </customValue>
    <masterLabel>CF Lead Source</masterLabel>
</GlobalValueSet>

src/globalValueSets/Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CleanQuote</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

classes/CreateObjectHandler.cls
public class CreateObjectHandler {

    public static Account checkAccDupes(String accName, Boolean bankingAcc) {
        String queryAcc = 'SELECT Id, Name FROM Account WHERE Name = :accName';
        List<Account> accToReturn = new List<Account>();
        if(bankingAcc) {
            queryAcc += ' AND Client_Status__c = \'Pre-Contact\' AND Type = \'Bank\'';
        }
        queryAcc += ' LIMIT 1';
        accToReturn = Database.query(queryAcc);
        if(accToReturn.size() > 0) {
            return accToReturn[0];
        } else {
            return null;
        }
    }
    
    public static Contact searchContactDupes(String email, String firstName, String lastName) {
        List<Contact> contactToCheck = new List<Contact>([SELECT Id, AccountId, Account.Name FROM Contact WHERE Email = :email AND FirstName = :firstName AND LastName = :lastName]);
        if(contactToCheck.size() > 0) {
            return contactToCheck[0];
        } else {
            return null;
        }
    }
    
    public static Contact createOrUpdateContact(String email, String firstName, String lastName, String phone, String inputAccountId, String objId) {
        Contact contactToInsert = new Contact();
            contactToInsert.Can_contact_with_marketing_materials__c = 'Yes';
            contactToInsert.LeadSource = 'CleanQuote';
            contactToInsert.Sub_Lead_Source__c = 'CleanQuote';
        	if(!String.isEmpty(inputAccountId)) {
            	contactToInsert.AccountId = inputAccountId;
        	}
        	contactToInsert.Email = email;
        	contactToInsert.FirstName = firstName;
        	contactToInsert.LastName = lastName;
        	contactToInsert.Phone = phone;
        	if(!String.isEmpty(objId)) {
				contactToInsert.Id = objId;
            	update contactToInsert;
        	} else {
            	insert contactToInsert;
        	}
        return contactToInsert;
    }
    
    public static Account createOrUpdateAccount(String accName, String inputLeadSource, String city, String state, String streetAddress, String zipCode, String EntityType, String objId) {
        Account accToInsert = new Account(Name = accName);
        System.debug(accToInsert);
        accToInsert.Client_Status__c = 'Pre-Contact';
        if(inputLeadSource == 'Web Quote Owner') {
            accToInsert.Type = 'Owner';     
        } else {
            if(inputLeadSource == 'Web Quote Owner Rep') {
                accToInsert.Type = 'Owner Rep'; 
            }
        }
        accToInsert.CF_Lead_Source__c = 'CleanQuote';
        accToInsert.City__c = city;
        accToInsert.State__c = state;
        accToInsert.Street_Address__c = streetAddress;
        accToInsert.Zip_Code__c = zipCode;
        accToInsert.Entity_Type__c = EntityType;
        if(!String.isEmpty(objId)) {
			accToInsert.Id = objId;
            update accToInsert;
        } else {
            insert accToInsert;
        }
        return accToInsert;
    }
    
    public static CreateRecordsWrapper stringifyRecord(CreateRecordsWrapper inputWrapperVar) {
        if(String.isEmpty(inputWrapperVar.AccName)) {
            inputWrapperVar.AccName = '';
        }
        if(String.isEmpty(inputWrapperVar.ISPARTNERACC)) {
            inputWrapperVar.ISPARTNERACC = 'false';
        }
        if(String.isEmpty(inputWrapperVar.LEADSOURCE)) {
            inputWrapperVar.LEADSOURCE = '';
        }
        if(String.isEmpty(inputWrapperVar.EMAIL)) {
            inputWrapperVar.EMAIL = '';
        }
        if(String.isEmpty(inputWrapperVar.FIRSTNAME)) {
            inputWrapperVar.FIRSTNAME = '';
        }
        if(String.isEmpty(inputWrapperVar.LASTNAME)) {
            inputWrapperVar.LASTNAME = '';
        }
        if(String.isEmpty(inputWrapperVar.PHONE)) {
            inputWrapperVar.PHONE = '';
        }
        if(String.isEmpty(inputWrapperVar.CITY)) {
            inputWrapperVar.CITY = '';
        }
        if(String.isEmpty(inputWrapperVar.STATE)) {
            inputWrapperVar.STATE = '';
        }
        if(String.isEmpty(inputWrapperVar.STREETADDRESS)) {
            inputWrapperVar.STREETADDRESS = '';
        }
        if(String.isEmpty(inputWrapperVar.ZIPCODE)) {
            inputWrapperVar.ZIPCODE = '';
        }
        if(String.isEmpty(inputWrapperVar.ENTITYTYPE)) {
            inputWrapperVar.ENTITYTYPE = '';
        }
        return inputWrapperVar;
    }
}