src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <inlineHelpText>If this account record represents a property owner, or some entity connected to an opportunity.  Then the entity information should be filled in.</inlineHelpText>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Date__c</fullName>
        <label>Acquisition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CF_Sub_Lead_Source__c</fullName>
        <description>Name the specific Lead Source.</description>
        <label>CF Sub-Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadConvertUtilTest.cls
/**
Test class for LeadConvertUtil
13.02.2018 Rodion Vakulovskyi created class
**/
@isTest
public class LeadConvertUtilTest {
    
    private static testmethod void testLeadConvertUtilString() {
        Lead leadToInsert = TestHelperUtility.createLead();
        leadToInsert.Entity_Type__c = 'Partnership';
        Account accToTest = (Account)LeadConvertUtil.processLeadConvertionWithObject(leadToInsert, 'Account');
    }
    
    private static testmethod void testLeadConvertUtilDate() {
        Lead leadToInsert = TestHelperUtility.createLead();
        leadToInsert.Acquisition_Date__c = Date.today();
        Test.startTest();
        	Opportunity oppToTest = (Opportunity)LeadConvertUtil.processLeadConvertionWithObject(leadToInsert, 'Opportunity');
        Test.stopTest();
    }

    private static testmethod void testLeadRequiredPage() {
        Test.startTest();
         Lead leadToInsert = TestHelperUtility.createLead();
         leadToInsert.LastName = 'Test';
         leadToInsert.Company = 'Test';
         leadToInsert.CF_Sub_Lead_Source__c = 'erwr';
         insert leadToInsert;
         ApexPages.StandardController sc = new ApexPages.StandardController(leadToInsert);
         RequiredLeadConversionCntr leadTest = new RequiredLeadConversionCntr(sc);
         List<Schema.FieldSetMember> listFieldSet = leadTest.getFieldsAccount();
         List<Schema.FieldSetMember> listFieldSet2 = leadTest.getFieldsContact();
         List<Schema.FieldSetMember> listFieldSet3 = leadTest.getFieldsOpp();
      //   System.assertEquals(true, listFieldSet.size() > 0, 'Size should me more then 0');
        // System.assertEquals(null,errorMsg, 'Return message should be empty');
       Test.stopTest();
    }
}