src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Capitalized_Interest__c</fullName>
        <label>Capitalized Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Channel_Partner_Fee_Percent__c</fullName>
        <formula>IF(ISPICKVAL(  Channel_Partner_Entity__r.Active_Affiliate_Agreement__r.Affiliate_Fee_Based_On__c , &quot;CleanFund Fee&quot;),
 Total_Financing_Fee__c * Channel_Partner__c, Channel_Partner__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Channel Partner Origination Fee normalized to Project Cost</inlineHelpText>
        <label>Channel Partner Fee (%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CleanFund_Fee_Orig_percent__c</fullName>
        <formula>IF(ISPICKVAL(  Channel_Partner_Entity__r.Active_Affiliate_Agreement__r.Affiliate_Fee_Based_On__c , &quot;CleanFund Fee&quot;),
 Total_Financing_Fee__c * (1-Channel_Partner__c), Total_Financing_Fee__c - Channel_Partner__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>CleanFund Origination Fee normalized to the Project Cost.</inlineHelpText>
        <label>CF Origination Fee (%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Est_Improvement_Cost__c</fullName>
        <description>Estimate of improvement cost, gross of financing and program fees</description>
        <inlineHelpText>Estimated cost of all improvements.</inlineHelpText>
        <label>C-PACE Project Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financing_Amount__c</fullName>
        <description>Financing Amount associated with Opportunity</description>
        <label>Total PACE financing amount (Est.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Prop__c</fullName>
        <label>State - Property</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sources_and_Use__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sources and Use</label>
    <pluralLabel>Sources and Uses</pluralLabel>
</CustomObject>

src/objects/Sources_Uses__c.object
<CustomObject>
    <description>Object to keep track of individual line item on Sources &amp; Uses</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Type of Source/Use (COI, etc.)</description>
        <inlineHelpText>Type of Source/Use (COI, etc.)</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Source</fullName>
                </value>
                <value>
                    <fullName>Cost of Issuance</fullName>
                </value>
                <value>
                    <fullName>Capitalized Interest Sub-Account</fullName>
                </value>
                <value>
                    <fullName>Bond Reserve</fullName>
                </value>
                <value>
                    <fullName>C-PACE Project Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Closing_Cost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closing Cost?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sources &amp; Uses</relationshipLabel>
        <relationshipName>Sources_Uses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Party__c</fullName>
        <label>Party</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Or_Use__c</fullName>
        <label>Source Or Use?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Source</fullName>
                </value>
                <value>
                    <fullName>Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Use_Type__c</fullName>
        <description>Type of Source/Use</description>
        <inlineHelpText>Type of Source/Use</inlineHelpText>
        <label>Source/Use Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                </value>
                <value>
                    <fullName>Base Program Admin</fullName>
                </value>
                <value>
                    <fullName>Capitalized Interest</fullName>
                </value>
                <value>
                    <fullName>CDIAC Fee (Bond Reserve)</fullName>
                </value>
                <value>
                    <fullName>CleanFund Financing Fee</fullName>
                </value>
                <value>
                    <fullName>Fee Adjustment</fullName>
                </value>
                <value>
                    <fullName>Fiscal Agent</fullName>
                </value>
                <value>
                    <fullName>Fiscal Agent (Bond Reserve)</fullName>
                </value>
                <value>
                    <fullName>Issuer Legal Counsel (at close)</fullName>
                </value>
                <value>
                    <fullName>Issuer Legal Counsel (Bond Reserve)</fullName>
                </value>
                <value>
                    <fullName>PACE Assessment (Total Assessment Amount)</fullName>
                </value>
                <value>
                    <fullName>Program Administration Fee</fullName>
                </value>
                <value>
                    <fullName>Program Sponsor (at close)</fullName>
                </value>
                <value>
                    <fullName>Program Sponsor (Bond Reserve)</fullName>
                </value>
                <value>
                    <fullName>Project Amount</fullName>
                </value>
                <value>
                    <fullName>Recordation Fee</fullName>
                </value>
                <value>
                    <fullName>Tax Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Source &amp; Use</label>
    <nameField>
        <label>Sources &amp; Uses Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources &amp; Uses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Account_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>Industry Association</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

src/classes/SourceAndUserCntr.cls
public class SourceAndUserCntr {
    public Opportunity inputOpp{get;set;}
    public static final String FIELDLIST = 'List Of Types';
    public static final String TYPELIST = 'Field List';
    Map<String, sObject> mapOfFieldsetsToStage{get;set;}
    public String programAdminFee1{get;set;}
    public String programAdminFee2{get;set;}
    public String legalCouncelFee1{get;set;}
    public String legalCouncelFee2{get;set;}
    public String legalCouncelBondFee1{get;set;}
    public String legalCouncelBondFee2{get;set;}
    public String AgentFee1{get;set;}
    public String AgentFee2{get;set;}
    public String AgentReserveFee1{get;set;}
    public String AgentReserveFee2{get;set;}
    public String sponsorFee1{get;set;}
    public String sponsorResFee1{get;set;}
    public String sponsorMandFee1{get;set;}
    public String sponsorMandFee2{get;set;}
    public String recordationFee1{get;set;}
    public String recordationFee2{get;set;}
    public String taxFee1{get;set;}
    public String taxFee2{get;set;}
    public String govFee{get;set;}
    public String appFee{get;set;}

    
    public SourceAndUserCntr(ApexPages.StandardController stdController) {
        mapOfFieldsetsToStage = ApexHelperUtility.queryAllMetaByTypeLabel('Sources_and_Use__mdt');
        System.debug(mapOfFieldsetsToStage);
        Sources_and_Use__mdt sourceAndUser = (Sources_and_Use__mdt)mapOfFieldsetsToStage.get(TYPELIST);
        List<String> listOfQueryFields = sourceAndUser.Value__c.split(',');
        System.debug(listOfQueryFields);
        if(!Test.isRunningTest()){
        	stdController.addFields(listOfQueryFields);
            this.inputOpp = (Opportunity)stdController.getRecord();
        } else {
            this.inputOpp = (Opportunity)stdController.getRecord();
            this.inputOpp = [SELECT Id, Est_Improvement_Cost__c, CleanFund_Fee_Orig_percent__c, Capitalized_interest__c, Financing_Amount__c, Channel_Partner_Fee_Percent__c, State_Prop__c FROM Opportunity WHERE Id = :inputOpp.Id];
        }
        
    }

    public PageReference createSourceAndUser() {
        PageReference pageRef;
        List<Sources_Uses__c> listToInsert = new List<Sources_Uses__c>();
        Sources_and_Use__mdt sourceAndUser = (Sources_and_Use__mdt)mapOfFieldsetsToStage.get(FIELDLIST);
        try{
            inputOpp.Est_Improvement_Cost__c = inputOpp.Est_Improvement_Cost__c != null ? inputOpp.Est_Improvement_Cost__c : 0;
        	for(String itemString : sourceAndUser.Value__c.split(',')) {
                if(itemString == 'CleanFund Financing Fee') {
                    Decimal amount = inputOpp.Est_Improvement_Cost__c * inputOpp.CleanFund_Fee_Orig_percent__c != null ? inputOpp.Est_Improvement_Cost__c * inputOpp.CleanFund_Fee_Orig_percent__c : 0;
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', 'CleanFund Commercial PACE Capital', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Program Administration Fee') {
                    Decimal amount = Decimal.valueOf(programAdminFee1)/100 * inputOpp.Est_Improvement_Cost__c  + Decimal.valueOf(programAdminFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', '', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Capitalized Interest') {
                    Decimal amount = inputOpp.Capitalized_interest__c != null ? inputOpp.Capitalized_interest__c : 0;//Capitalized_interest__c
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Capitalized Interest Sub-Account', true, '', '', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Issuer Legal Counsel (at close)') {
                    Decimal amount = (Decimal.valueOf(legalCouncelFee1)/100 * inputOpp.Est_Improvement_Cost__c) + Decimal.valueOf(legalCouncelFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', '', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Issuer Legal Counsel (Bond Reserve)') {
                    Decimal amount = (Decimal.valueOf(legalCouncelBondFee1)/100 * inputOpp.Est_Improvement_Cost__c) + Decimal.valueOf(legalCouncelBondFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Bond Reserve', true, '', '', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Appraisal Reimbursement') {
                    Decimal amount = Decimal.valueOf(appFee);//Appraisal Fee
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, 'Only if we are reimbursing the appraisal fee through financing (users responsibility)', 'Property Owner/CleanFund', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'CDIAC Fee (Bond Reserve)') {
                    Decimal amount = inputOpp.Financing_Amount__c != null ? (0.0025 * inputOpp.Financing_Amount__c) : 0;
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Bond Reserve', true, '', 'CDIAC', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Channel Partner Fee') {
                    Decimal amount = inputOpp.Channel_Partner_Fee_Percent__c * inputOpp.Est_Improvement_Cost__c;
                    if(amount != 0) {
                        listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', 'Channel Partner', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Fiscal Agent (Bond Reserve)') {
                    Decimal amount = Decimal.valueOf(AgentFee1)/100 * inputOpp.Est_Improvement_Cost__c + Decimal.valueOf(AgentFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', '', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Fiscal Agent (Reserve)') {
                    Decimal amount = Decimal.valueOf(AgentReserveFee1)/100 * inputOpp.Est_Improvement_Cost__c + Decimal.valueOf(AgentReserveFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Bond Reserve', true, '', '', 'Use', itemString, amount));
                    }
                }
                 if(itemString == 'PACE Assessment (Total Assessment Amount)') {
                    Decimal amount = inputOpp.Financing_Amount__c!= null ? inputOpp.Financing_Amount__c : 0;
                     if(amount != 0) {
                    listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Source', true, '', 'Property Owner', 'Source', itemString, amount));
                     }
                }
                if(itemString == 'Program Sponsor (At Close)') {
                    Decimal amount = Decimal.valueOf(sponsorFee1)/100 * inputOpp.Est_Improvement_Cost__c;
                    if(!String.isEmpty(sponsorMandFee1) && amount < Decimal.valueOf(sponsorMandFee1)) {
                        amount = Decimal.valueOf(sponsorMandFee1);
                    }
                    if(!String.isEmpty(sponsorMandFee2) && amount > Decimal.valueOf(sponsorMandFee2)) {
                        amount = Decimal.valueOf(sponsorMandFee2);
                    }
                    if(amount != 0 && !String.isEmpty(sponsorMandFee2)) {
                    listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, 'Adjust up if below mandatory minimum, adjust down if below mandatory maximum (if min or max are 0, skip this step)', 'Program Sponsor', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Program Sponsor (Bond Reserve)') {
                    System.debug(sponsorResFee1);
                    Decimal amount = Decimal.valueOf(sponsorResFee1)/100 * inputOpp.Est_Improvement_Cost__c;
                    if(!String.isEmpty(sponsorMandFee1) && amount < Decimal.valueOf(sponsorMandFee1)) {
                        amount = Decimal.valueOf(sponsorMandFee1);
                    }
                    if(!String.isEmpty(sponsorMandFee2) && amount > Decimal.valueOf(sponsorMandFee2)) {
                        amount = Decimal.valueOf(sponsorMandFee2);
                    }
                    if(amount != 0 && !String.isEmpty(sponsorMandFee2)) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Bond Reserve', true, 'Adjust up if below mandatory minimum, adjust down if below mandatory maximum (if min or max are 0, skip this step)', 'Program Sponsor', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Project Amount') {
                    Decimal amount = inputOpp.Est_Improvement_Cost__c != null ? inputOpp.Est_Improvement_Cost__c : 0;
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'C-PACE Project Account', true, 'Revisit later for breaking down into component pieces', 'Property Owner', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Recordation Fee') {
                    Decimal amount = (Decimal.valueOf(recordationFee1)/100 * inputOpp.Est_Improvement_Cost__c) + Decimal.valueOf(recordationFee2);
                    if(amount != 0) {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, '', 'Program Administrator', 'Use', itemString, amount));
                    }
                }
                if(itemString == 'Tax Administrator') {
                    Decimal amount = (Decimal.valueOf(taxFee1)/100 * inputOpp.Est_Improvement_Cost__c) + Decimal.valueOf(taxFee2);
                    if(amount != 0 && inputOpp.State_Prop__c  == 'CA') {
                    	listToInsert.add(formSourceAndUseRecord(inputOpp.Id, 'Cost of Issuance', true, 'Only create if Opportunity State = CA', 'Tax Administrator', 'Use', itemString, amount));
                    }
                }
        	}
            insert listToInsert;
            pageRef = new PageReference('/' + inputOpp.Id);
        } catch(Exception ex) {
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error, ex.getMessage()));
            	System.debug(ex.getMessage());
                pageRef = null;
        }
        return pageRef;
    }
    
    public Pagereference cancel() {
		return new Pagereference('/' + inputOpp.Id);        
    }
    
    private Sources_Uses__c formSourceAndUseRecord(String oppId, String accType, Boolean closingCost, String notes, String party, String sourceOrUse, String sourceUseType, Decimal amount) {
		Sources_Uses__c sourceRecord = new Sources_Uses__c(
            							Opportunity__c  = oppId,
            							Account_Type__c = accType,
            							Closing_Cost__c = closingCost,
            							Notes__c = notes,
            							Party__c = party,
            							Source_Use_Type__c  = sourceUseType,
            							Source_Or_Use__c = sourceOrUse,
            							Amount__c = amount
        								);
     	return sourceRecord;
    }

}