src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccTypeNew__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <inlineHelpText>If this account record represents a property owner, or some entity connected to an opportunity.  Then the entity information should be filled in.</inlineHelpText>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CleanQuoteUser__c.object
<CustomObject>
    <description>The user information for CleanQuote</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <inlineHelpText>The First Name of the User Register</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Property_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates if this contact is a property owner.</inlineHelpText>
        <label>Is Property Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <inlineHelpText>The Last Name of the User Registered</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <inlineHelpText>The Phone Number of the User Registered.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <label>CleanQuoteUser</label>
    <nameField>
        <label>CleanQuoteUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CleanQuoteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Property_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates whether this contact is a property owner.</inlineHelpText>
        <label>Is Property Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.Street_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <formula>Account.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GlobalAccType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
        <label>Lender</label>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>City</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>County</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
        <default>true</default>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Third party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>GlobalAccType</masterLabel>
</GlobalValueSet>

src/classes/CleanQuoteUserCntr.cls
public class CleanQuoteUserCntr  {
    public CleanQuoteUser__c cqUser{get;set;}
    public String objectPicker{get;set;}
    public CleanQuoteUserCntr(ApexPages.StandardController stdController) {
        this.cqUser = (CleanQuoteUser__c)stdController.getRecord();
         cqUser = (CleanQuoteUser__c)ApexHelperUtility.queryAllFieldsObject('CleanQuoteUser__c', cqUser.Id);
    }

    public List<SelectOption> getObjectPickerList() {
        List<SelectOption> listToReturn = new List<SelectOption>();
            listToReturn.add(new SelectOption('none','--None--'));
            listToReturn.add(new SelectOption('accToConvert','Account'));
            listToReturn.add(new SelectOption('contactToConvert','Contact'));
        return listToReturn;
    }

    public String convertContact() {
        Contact contToConvert = checkContactDupe(cqUser);
        if(contToConvert == null) {
            contToConvert = new Contact(
                                                Is_Property_Owner__c = true,
                                                FirstName = cqUser.First_Name__c,
                                                LastName = cqUser.Last_Name__c,
                                                Phone = cqUser.Phone__c,
                                                Email = cqUser.Email__c,
                                                Title = cqUser.Title__c
                                    );
            insert  contToConvert;
        }
        return contToConvert.Id;
    }

    public String convertAccount() {
        Account accToConvert = checkAccountDupe(cqUser);
        if(accToConvert == null) {
            accToConvert = new Account(
                                        AccTypeNew__c = 'Owner',
                                        Name = cqUser.Company_Name__c
                                       );
            insert accToConvert;
        }
        return accToConvert.Id;
    }

    public Contact checkContactDupe(CleanQuoteUser__c inputCQUser) {
        List<Contact> contactToCheck = new List<Contact>([SELECT Id, FirstName, LastName, Email, Phone FROM Contact WHERE Email = :inputCQUser.Email__c AND FirstName = :inputCQUser.First_Name__c AND LastName = :inputCQUser.Last_Name__c]);
        if(contactToCheck.size() > 0) {
            return contactToCheck[0];
        } else {
            return null;
        }

    }

    public Account checkAccountDupe(CleanQuoteUser__c inputCQUser) {
        String accName = inputCQUser.Company_Name__c;
        String queryAcc = 'SELECT Id, City__c, State__c, Street_Address__c, Zip_Code__c, Entity_Type__c, Type, Name FROM Account WHERE Name = :accName';
        List<Account> accToReturn = new List<Account>();
        queryAcc += ' LIMIT 1';
        accToReturn = Database.query(queryAcc);
        if(accToReturn.size() > 0) {
            return accToReturn[0];
        } else {
            return null;
        }
    }

    public List<Schema.FieldSetMember> getFieldsContact() {
       List<Schema.FieldSetMember> listToReturn = new List<Schema.FieldSetMember>();
       listToReturn = SObjectType.CleanQuoteUser__c.FieldSets.CQContact.getFields();
       return listToReturn;
    }
    
    public List<Schema.FieldSetMember> getFieldsAccount() {
       List<Schema.FieldSetMember> listToReturn = new List<Schema.FieldSetMember>();
       listToReturn = SObjectType.CleanQuoteUser__c.FieldSets.CQAccount.getFields();
       return listToReturn;
    }

    public PageReference convertCQUser() {
        PageReference pageRefToRet = null;
        Savepoint savepoint = Database.setSavepoint();
        try{
            update cqUser;
            if(objectPicker == 'accToConvert') {
                pageRefToRet = new PageReference('/'+convertAccount());
            }
            if(objectPicker == 'contactToConvert') {
                pageRefToRet = new PageReference('/'+convertContact());
            }
        } catch(Exception ex) {
            Database.rollback(savepoint);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }   
        return pageRefToRet;
    }

    public PageReference cancel() {
        return new PageReference('/'+cqUser.Id);
    }
}