src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Financial_Crime__c</fullName>
        <inlineHelpText>This indicates whether the Property Owner has been convicted of a financial crime.</inlineHelpText>
        <label>Financial Crime</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Financial_Crime__c</fullName>
        <label>Financial Crime</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub-Lead Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Financial_Crime__c</fullName>
        <inlineHelpText>Has the Owner Entity (or its Coporate Parent) or any related party to the transaction, been convicted of any crime, or subject to any regulatory action, in the past seven years</inlineHelpText>
        <label>Financial Crime</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Only</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owner_Occupied__c</fullName>
        <label>Owner Occupied</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Only</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Purchase_Price__c</fullName>
        <label>Property Purchase Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Revenue__c</fullName>
        <inlineHelpText>The annual amount of money that is brought into a company by its business activities.</inlineHelpText>
        <label>Annual Business Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Crime__c</fullName>
        <inlineHelpText>This indicates whether the Property Owner has been convicted of a financial crime.</inlineHelpText>
        <label>Financial Crime</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>If_groundlease_expiration_date__c</fullName>
        <label>If ground lease, expiration date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_there_a_groundlease_in_place__c</fullName>
        <label>Is there a ground lease in place?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>Estimated loan term (not final)</description>
        <inlineHelpText>Desired length of financing term, expressed in years</inlineHelpText>
        <label>Financing Term</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <description>City or Municipality where property is located</description>
        <inlineHelpText>City property is located in</inlineHelpText>
        <label>City - Property</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Occupied__c</fullName>
        <inlineHelpText>This indicates whether the Property is occupied by the Owner or by tenants.</inlineHelpText>
        <label>Owner Occupied</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PACEPartner_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_City__c</fullName>
        <label>City (PACEPartner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACEPartner_Mailing_Zip_Code__c</fullName>
        <label>Zip Code (PACEPartner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address__c</fullName>
        <description>Physical adress of the building receiving the improvements</description>
        <inlineHelpText>Street adress of the building receiving the improvements</inlineHelpText>
        <label>Street Address - Property</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Property_Type__c</fullName>
        <inlineHelpText>Select the most relevant primary property type from the dropdown list.</inlineHelpText>
        <label>Primary Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Retail-Unanchored</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                </value>
                <value>
                    <fullName>Multifamily</fullName>
                </value>
                <value>
                    <fullName>Mixed Use</fullName>
                </value>
                <value>
                    <fullName>UNCATEGORIZED</fullName>
                </value>
                <value>
                    <fullName>Retail-Anchored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Purchase_Price__c</fullName>
        <inlineHelpText>Price the owner paid to acquire the property.</inlineHelpText>
        <label>Property Purchase Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <description>Sub-lead source for Opportunity to provide additional granularity</description>
        <label>Sub Lead Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>This is a Yes/No Picklist</description>
    <masterLabel>Yes/No/NA</masterLabel>
</GlobalValueSet>

classes/CustomOpportunitySaveExtensionTest.cls
@IsTest public without sharing class CustomOpportunitySaveExtensionTest
        {
        @IsTest(SeeAllData=true) public static void testCustomOpportunitySaveExtension()
        {
//                Opportunity opp;
//                List<Opportunity> opplst = [
//                                                SELECT Id
//                                                FROM Opportunity
//                                                LIMIT 1
//                                            ];
//
//                  if ( opplst.size() > 0 )
//                  {
//                      opp = opplst[0];
//                      system.debug('Successfully account retrieved ');
//                  }

                // set up opp and Verify that the results are as expected.
//                Opportunity o = new Opportunity(AccountId=null, Name=opportunityName,
//                        StageName='Pre-Qualified Lead', CloseDate=Date.today(), Loan_Term__c=20,
//                        LeadSource='Channel Partner', Sub_Lead_Source__c='Cool Patner');
//                insert o;
//                Opportunity opp = [SELECT Name FROM Opportunity WHERE Id = :o.Id];

                CustomOpportunityController controller = new CustomOpportunityController();
                controller.opportunityName = 'TestOpportunityName';
                controller.ppProjectNumber = '91919191734';
                controller.accountName     = 'Acct Test Opportunity';
                controller.companyName     = 'GowebEz';
                controller.mainContact     = 'Sakthivel Palanivelu';
                controller.pp_project_number   = '91919191734';


                controller.createOpportunity();

                Opportunity opp;

                List<Opportunity> opplst = [
                                                SELECT Id, Name
                                                FROM Opportunity
                                                WHERE Name = 'TestOpportunityName'
                                                LIMIT 1
                                            ];

                  if ( opplst.size() > 0 )
                  {
                      opp = opplst[0];
                      system.debug('Successfully opportunity retrieved ');
                  }

//                System.assertEquals('TestOpportunityName', opp.Name);

          
                Test.Starttest();
                ApexPages.StandardController stdController = new ApexPages.StandardController(opp);
                CustomOpportunitySaveExtension ext = new CustomOpportunitySaveExtension(stdController);
                ext.CheckAndValidate();
                System.assertNotEquals(ext.validationMessage,null);
            
                opp.Owner_Occupied__c = 'Yes';
                opp.Business_Revenue__c = null;
                opp.Financial_Crime__c = null;
                opp.Primary_Property_Type__c = 'Retail';
                opp.Physical_Address__c = null;
                opp.Municipality__c = null;
                opp.Property_Purchase_Price__c = null;
                opp.PACEPartner_Mailing_City__c = null;
                opp.PACEPartner_Email__c = null;
                opp.PACEPartner_Mailing_Zip_Code__c = null;


                UPDATE opp;
            
                system.debug('This is the owner_occupied value ' + opp.Owner_Occupied__c);
                system.debug('This is the Business_Revenue__c value ' + opp.Business_Revenue__c);
                system.debug('This is a new debug messagesddddddd.........' + ext.validationMessage);
                ext.CheckAndValidate();
                System.assert(ext.validationMessage.contains('Business Revenue'));
                System.assert(ext.validationMessage.contains('Financial Crime'));
                System.assert(!ext.validationMessage.contains('Primary Property'));
                System.assert(ext.validationMessage.contains('Property Information - City'));
                System.assert(ext.validationMessage.contains('Property Information - Street Addres'));
                System.assert(ext.validationMessage.contains('Property Information - Property Purchase Price'));
                System.assert(ext.validationMessage.contains('PACEPartner Contact Information - City'));
                System.assert(ext.validationMessage.contains('PACEPartner Contact Information - Email'));
                System.assert(ext.validationMessage.contains('PACEPartner Contact Information - Zip Code'));


                opp.Owner_Occupied__c = 'No';
                opp.Physical_Address__c = '123 Main';
                opp.Municipality__c = 'oakland';
                opp.Property_Purchase_Price__c = 10;
                opp.PACEPartner_Mailing_City__c = 'Alameda';
                opp.PACEPartner_Email__c = 'joe@example.com';
                opp.PACEPartner_Mailing_Zip_Code__c = '1234';

                UPDATE opp;
                ext.CheckAndValidate();
                system.debug('This is a new owner occupied.........' + ext.validationMessage);
                System.assert(!ext.validationMessage.contains('Property Information - Street Addres'));
                System.assert(!ext.validationMessage.contains('PACEPartner Contact Information - City'));
                System.assert(!ext.validationMessage.contains('PACEPartner Contact Information - Email'));
                System.assert(!ext.validationMessage.contains('PACEPartner Contact Information - Zip Code'));


                opp.Is_there_a_groundlease_in_place__c = 'Yes';
                opp.If_groundlease_expiration_date__c = null;
                UPDATE opp;
                ext.CheckAndValidate();
                System.assert(ext.validationMessage.contains('If groundlease, expiration date'));

                system.debug('This is the stage name........................ ' + opp.StageName);


                Test.Stoptest();
        }

   }