src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Sub_Type__c</fullName>
        <inlineHelpText>This is the entity subtype for the Property Owner</inlineHelpText>
        <label>Entity Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Entity_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint Tenants</fullName>
                </value>
                <value>
                    <fullName>General Partnership (GP)</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership (LP)</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Partnership (LLP)</fullName>
                </value>
                <value>
                    <fullName>Joint Venture</fullName>
                </value>
                <value>
                    <fullName>Single Member LLC</fullName>
                </value>
                <value>
                    <fullName>Multiple Member LLC</fullName>
                </value>
                <value>
                    <fullName>Professional Limited Liability Company (PLLC)</fullName>
                </value>
                <value>
                    <fullName>S Corp</fullName>
                </value>
                <value>
                    <fullName>C Corp</fullName>
                </value>
                <value>
                    <fullName>B Corp</fullName>
                </value>
                <value>
                    <fullName>Nonprofit</fullName>
                </value>
                <value>
                    <fullName>Revocable</fullName>
                </value>
                <value>
                    <fullName>Irrevocable</fullName>
                </value>
                <value>
                    <fullName>QTIP Trust</fullName>
                </value>
                <value>
                    <fullName>GST Trust</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <inlineHelpText>If this account record represents a property owner, or some entity connected to an opportunity.  Then the entity information should be filled in.</inlineHelpText>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Request_List__c.object
<CustomObject>
    <description>This is the document request list.  It will be a union of all documents required regardless of state, for each opportunity the list will be filtered for the appropriate documents.</description>
    <fields>
        <fullName>DRL_Template_ItemID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Describes the master:detail relationship DRL_Template_ItemID</description>
        <inlineHelpText>Describes the master:detail relationship DRL_Template_ItemID.</inlineHelpText>
        <label>DRL Template ItemID</label>
        <referenceTo>DRL_Template_Item__c</referenceTo>
        <relationshipLabel>Document Request Lists</relationshipLabel>
        <relationshipName>Document_Request_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name_Global__c</fullName>
        <description>Document_Name_Global</description>
        <inlineHelpText>Document_Name_Global</inlineHelpText>
        <label>Document Name Global</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes_and_Comments__c</fullName>
        <inlineHelpText>These will be included in reports that are going to the property owner.  It should be used to clarify the document request.</inlineHelpText>
        <label>Notes and Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>This is the document request list for an opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Document Request Lists</relationshipLabel>
        <relationshipName>Opportunity_DRL</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Responsible_Party__c</fullName>
        <inlineHelpText>Who is responsible for providing the document.</inlineHelpText>
        <label>Responsible Party</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CleanFund</fullName>
                </value>
                <value>
                    <fullName>Property Owner</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Tax Equity Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>When does this document go out?</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Stage 1 (Term Sheet)</fullName>
                </value>
                <value>
                    <fullName>Stage 2 (Letter of Intent)</fullName>
                </value>
                <value>
                    <fullName>Stage 3 (Due Diligence)</fullName>
                </value>
                <value>
                    <fullName>Stage 4 (Underwriting)</fullName>
                </value>
                <value>
                    <fullName>Stage 5 (Closing)</fullName>
                </value>
                <value>
                    <fullName>Post Closing</fullName>
                    <isActive>false</isActive>
                    <label>Post Closing</label>
                </value>
                <value>
                    <fullName>Prior to Application</fullName>
                    <isActive>false</isActive>
                    <label>Prior to Application</label>
                </value>
                <value>
                    <fullName>Prior to Commitment</fullName>
                    <isActive>false</isActive>
                    <label>Prior to Commitment</label>
                </value>
                <value>
                    <fullName>Prior to Docs Out</fullName>
                    <isActive>false</isActive>
                    <label>Prior to Docs Out</label>
                </value>
                <value>
                    <fullName>Prior to Funding</fullName>
                    <isActive>false</isActive>
                    <label>Prior to Funding</label>
                </value>
                <value>
                    <fullName>Prior to LOI</fullName>
                    <isActive>false</isActive>
                    <label>Prior to LOI</label>
                </value>
                <value>
                    <fullName>Prior to Lender Ack.</fullName>
                    <isActive>false</isActive>
                    <label>Prior to Lender Ack.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Request List</label>
    <nameField>
        <label>Document Request List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request List</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DRL_Template_Item__c.object
<CustomObject>
    <description>This is the template for the DRL.</description>
    <fields>
        <fullName>DRL_Template_Number_Map__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&quot;DRL-XXXX&quot;</defaultValue>
        <description>Describes the DRL_Template_Number_Map custom field.</description>
        <inlineHelpText>Example: DRL-0060</inlineHelpText>
        <label>DRL Template Number Map</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <inlineHelpText>The Item number will help sort the list.  1.1 or 1.A</inlineHelpText>
        <label>Item</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes_and_Comments__c</fullName>
        <inlineHelpText>This should be helpful text to aid the property owner know what we are looking for.</inlineHelpText>
        <label>Notes and Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Responsible_Party__c</fullName>
        <inlineHelpText>This is the who is responsible for getting the document.</inlineHelpText>
        <label>Responsible Party</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Responsible_Party</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Stage</valueSetName>
        </valueSet>
    </fields>
    <label>DRL Template Item</label>
    <nameField>
        <displayFormat>DRL-{0000}</displayFormat>
        <label>DRL Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Template Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>App_Executed_Date__c</fullName>
        <inlineHelpText>The date the application was signed.</inlineHelpText>
        <label>Application Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CF_Due_Diligence_Deposit__c</fullName>
        <inlineHelpText>In the event an appraisal deposit is being collected, place the value of that deposit here</inlineHelpText>
        <label>CF Due Diligence Deposit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_a_groundlease_in_place__c</fullName>
        <label>Is there a ground lease in place?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Property_Type__c</fullName>
        <inlineHelpText>Select the most relevant primary property type from the dropdown list.</inlineHelpText>
        <label>Primary Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Retail-Unanchored</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                </value>
                <value>
                    <fullName>Multifamily</fullName>
                </value>
                <value>
                    <fullName>Mixed Use</fullName>
                </value>
                <value>
                    <fullName>UNCATEGORIZED</fullName>
                </value>
                <value>
                    <fullName>Retail-Anchored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>What is the scope of the project?</description>
        <label>Project Scope</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Construction</fullName>
                </value>
                <value>
                    <fullName>Upgrade/Retrofit</fullName>
                </value>
                <value>
                    <fullName>Gut Rehab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solar_TPO_Structure__c</fullName>
        <description>Whether there a TPO is present, and if so, how it is structured.</description>
        <label>Solar TPO Structure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>Solar Lease</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Prop__c</fullName>
        <label>State - Property</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Document_Stage.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Stage 1 (Term Sheet)</fullName>
    </customValue>
    <customValue>
        <fullName>Stage 2 (Letter of Intent)</fullName>
    </customValue>
    <customValue>
        <fullName>Stage 3 (Due Diligence)</fullName>
    </customValue>
    <customValue>
        <fullName>Stage 4 (Underwriting)</fullName>
    </customValue>
    <customValue>
        <fullName>Stage 5 (Closing)</fullName>
    </customValue>
    <customValue>
        <fullName>Post Closing</fullName>
        <isActive>false</isActive>
        <label>Post Closing</label>
    </customValue>
    <customValue>
        <fullName>Prior to Docs Out</fullName>
        <isActive>false</isActive>
        <label>Prior to Docs Out</label>
    </customValue>
    <customValue>
        <fullName>Prior to Commitment</fullName>
        <isActive>false</isActive>
        <label>Prior to Commitment</label>
    </customValue>
    <customValue>
        <fullName>Prior to Lender Ack.</fullName>
        <isActive>false</isActive>
        <label>Prior to Lender Ack.</label>
    </customValue>
    <customValue>
        <fullName>Prior to LOI</fullName>
        <isActive>false</isActive>
        <label>Prior to LOI</label>
    </customValue>
    <customValue>
        <fullName>Prior to Application</fullName>
        <isActive>false</isActive>
        <label>Prior to Application</label>
    </customValue>
    <customValue>
        <fullName>Prior to Funding</fullName>
        <isActive>false</isActive>
        <label>Prior to Funding</label>
    </customValue>
    <description>The stage that a DRL is required.</description>
    <masterLabel>Document Stage</masterLabel>
</GlobalValueSet>

src/globalValueSets/Responsible_Party.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CleanFund</fullName>
    </customValue>
    <customValue>
        <fullName>Property Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Tax Equity Provider</fullName>
    </customValue>
    <masterLabel>Responsible Party</masterLabel>
</GlobalValueSet>

src/classes/DocumentRequestListUtilities.cls
/**
* @author Conga
* @author Joseph Markey
* @Edited by Brendan Neal 5/15/2018
* @version 1.01
* @description describes the DocumentRequestListUtilities class
*/
public with sharing class DocumentRequestListUtilities {
    public Opportunity opp;

    // constructor
    public DocumentRequestListUtilities(ApexPages.StandardController stdController) {
        this.opp = (Opportunity)stdController.getRecord();
    }

    @RemoteAction
    public static void generateDocumentRequestList(Id pOppId) {
        // query this Opportunity record
        Opportunity thisOpp = [
            SELECT Id, Name, State_Prop__c, Solar_TPO_Structure__c, App_Executed_Date__c, Is_there_a_groundlease_in_place__c, CF_Due_Diligence_Deposit__c, Account.Entity_Type__c, Primary_Property_type__c, Account.Entity_Sub_Type__c, Project_Type__c
            FROM Opportunity
            WHERE Id = :pOppId
        ];
        // instantiate a new, empty Document_Request_List__c list
        List<Document_Request_List__c> documentRequestList = new List<Document_Request_List__c>();
        List<DRL_Template_Item__c> itemList = [SELECT Id, Name, Item__c, Document_Name__c, DRL_Template_Number_Map__c, Notes_and_Comments__c, Responsible_Party__c, Stage__c FROM DRL_Template_Item__c];
        for(DRL_Template_Item__c item : itemList) {
            // add standard documents
            if(item.DRL_Template_Number_Map__c=='DRL-0001' || item.DRL_Template_Number_Map__c=='DRL-0002' ||
               item.DRL_Template_Number_Map__c=='DRL-0003' || item.DRL_Template_Number_Map__c=='DRL-0004' || 
               item.DRL_Template_Number_Map__c=='DRL-0006' || item.DRL_Template_Number_Map__c=='DRL-0007' || 
               item.DRL_Template_Number_Map__c=='DRL-0008' || item.DRL_Template_Number_Map__c=='DRL-0010' || 
               item.DRL_Template_Number_Map__c=='DRL-0011' || item.DRL_Template_Number_Map__c=='DRL-0018' || 
               item.DRL_Template_Number_Map__c=='DRL-0019' || item.DRL_Template_Number_Map__c=='DRL-0020' || 
               item.DRL_Template_Number_Map__c=='DRL-0021' || item.DRL_Template_Number_Map__c=='DRL-0023' || 
               item.DRL_Template_Number_Map__c=='DRL-0024' || item.DRL_Template_Number_Map__c=='DRL-0028' || 
               item.DRL_Template_Number_Map__c=='DRL-0029' || item.DRL_Template_Number_Map__c=='DRL-0030' || 
               item.DRL_Template_Number_Map__c=='DRL-0031' || item.DRL_Template_Number_Map__c=='DRL-0032' || 
               item.DRL_Template_Number_Map__c=='DRL-0033' || item.DRL_Template_Number_Map__c=='DRL-0036' || 
               item.DRL_Template_Number_Map__c=='DRL-0037' || item.DRL_Template_Number_Map__c=='DRL-0042' || 
               item.DRL_Template_Number_Map__c=='DRL-0043' || item.DRL_Template_Number_Map__c=='DRL-0044' || 
               item.DRL_Template_Number_Map__c=='DRL-0045' || item.DRL_Template_Number_Map__c=='DRL-0046') {
                Document_Request_List__c documentRequestObjStandard = new Document_Request_List__c(
                    // assign the non-standard fields
                    DRL_Template_ItemID__c = item.Id,
                    Document_Name_Global__c = item.Document_Name__c,
                    Notes_and_Comments__c = item.Notes_and_Comments__c,
                    Responsible_Party__c = item.Responsible_Party__c,
                    Stage__c = item.Stage__c,
                    Item__c = item.Item__c,
                    // assign the standard fields
                    Opportunity__c = thisOpp.Id,
                    Status__c = 'Open'
                );
                documentRequestList.add(documentRequestObjStandard);
            }

            // add non-stadard documents
            //NewCon or Gut Rehab
            if(thisOpp.Project_Type__c=='New Construction' || thisOpp.Project_Type__c=='Gut Rehab') {
                if(item.DRL_Template_Number_Map__c=='DRL-0005' || item.DRL_Template_Number_Map__c=='DRL-0012' || item.DRL_Template_Number_Map__c=='DRL-0013' || item.DRL_Template_Number_Map__c=='DRL-0034') {
                    Document_Request_List__c documentRequestObjStandard2 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard2);
                }
            }
            
             //Ground Lease
            if(thisOpp.Is_there_a_groundlease_in_place__c == 'Yes') {
                if(item.DRL_Template_Number_Map__c=='DRL-0009') {
                    Document_Request_List__c documentRequestObjStandard3 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard3);
                }
            }
            
             //Hospitality shenanigans
            if(thisOpp.Primary_Property_Type__c == 'Hospitality') {
                if(item.DRL_Template_Number_Map__c=='DRL-0014' || item.DRL_Template_Number_Map__c=='DRL-0015' || item.DRL_Template_Number_Map__c=='DRL-0016') {
                    Document_Request_List__c documentRequestObjStandard4 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard4);
                }
            }
            
            //More Hospitality shenanigans
            if(thisOpp.Primary_Property_Type__c == 'Hospitality' && thisOpp.Project_Type__c == 'Upgrade/Retrofit') {
                if(item.DRL_Template_Number_Map__c=='DRL-0017') {
                    Document_Request_List__c documentRequestObjStandard5 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard5);
                }
            }
            
            //Entities that aren't Trusts
            if(thisOpp.Account.Entity_Type__c != 'Trust') {
                if(item.DRL_Template_Number_Map__c=='DRL-0022' || item.DRL_Template_Number_Map__c=='DRL-0025' || item.DRL_Template_Number_Map__c=='DRL-0026' || item.DRL_Template_Number_Map__c=='DRL-0027') {
                    Document_Request_List__c documentRequestObjStandard6 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard6);
                }
            }
            
            //Entities that aren't Trusts
            if(thisOpp.Solar_TPO_Structure__c == 'PPA') {
                if(item.DRL_Template_Number_Map__c=='DRL-0038' || item.DRL_Template_Number_Map__c=='DRL-0039' || item.DRL_Template_Number_Map__c=='DRL-0040' || item.DRL_Template_Number_Map__c=='DRL-0041') {
                    Document_Request_List__c documentRequestObjStandard7 = new Document_Request_List__c(
                        // assign the non-standard fields
                        DRL_Template_ItemID__c = item.Id,
                        Document_Name_Global__c = item.Document_Name__c,
                        Notes_and_Comments__c = item.Notes_and_Comments__c,
                        Responsible_Party__c = item.Responsible_Party__c,
                        Stage__c = item.Stage__c,
                        Item__c = item.Item__c,
                        // assign the standard fields
                        Opportunity__c = thisOpp.Id,
                        Status__c = 'Open'
                    );
                    documentRequestList.add(documentRequestObjStandard7);
                }
            }

            
        }

        // first, delete all of this Opportunity Document_Request_List__c related list items
        delete [SELECT Id, Opportunity__c FROM Document_Request_List__c WHERE Opportunity__c = :pOppId];

        // finally, insert the new Opportunity Document_Request_List__c related list items
        insert documentRequestList; 
    }

}