src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccTypeNew__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Status__c</fullName>
        <description>The current status of the client.</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Egnyte__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Egnyte</label>
</CustomObject>

src/objects/EgnyteGeneral__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Egnyte General</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AccountTypeNew__c</fullName>
        <description>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</description>
        <inlineHelpText>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Sub_Lead_Source__c</fullName>
        <description>Name the specific Lead Source.</description>
        <label>CF Sub-Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Run_Duplicate_Rules__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>An indication whether to run duplication rules or not.</inlineHelpText>
        <label>Run Duplicate Rules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/CF_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor on Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search (Outbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry (Inbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
        <isActive>false</isActive>
        <label>Website Inquiry</label>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
        <isActive>false</isActive>
        <label>Web Search</label>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
        <isActive>false</isActive>
        <label>UNKNOWN</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
        <isActive>false</isActive>
        <label>Journal</label>
    </customValue>
    <masterLabel>CF Lead Source</masterLabel>
</GlobalValueSet>

src/globalValueSets/GlobalAccType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
        <label>Lender</label>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>City</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>County</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
        <default>true</default>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Third party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>GlobalAccType</masterLabel>
</GlobalValueSet>

src/globalValueSets/Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CleanQuote</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

src/classes/LeadTriggerHandlerTest.cls
@isTest
public class LeadTriggerHandlerTest {
    
    
    @isTest 
    public static void autoConvertOnCreate(){
        createCustomSetting();
        Test.setMock(HttpCalloutMock.class, new EgnyteHttpCalloutImpl());
        Account testAccount = new Account(Name='TestAccount1',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Lead testlead = new Lead(LastName='TestLead1',Company='TestAccount1',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test', Run_Duplicate_Rules__c = true);
        Test.startTest();
        insert testAccount;
        insert testLead;
        Test.stopTest();
        
        //System.assert(testLead.IsConverted);   
    }
    @isTest
    public static void autoConvertOnUpdate(){
        createCustomSetting();
        Test.setMock(HttpCalloutMock.class, new EgnyteHttpCalloutImpl());
        Account testAccount = new Account(Name='TestAccount1',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Lead testlead = new Lead(LastName = 'testLead2',Company = 'test1',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        Lead testlead3 = new Lead(LastName = 'testLead1',Company = 'test2',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        List<Lead> toUpdate = new List<Lead>();
        test.startTest();
        insert testAccount;
        insert testLead3;
        insert testLead;
        List<Lead> testLead2 = new List<Lead>([Select id, LastName, Company from Lead where Company ='test' limit 1]);
        if (!testlead2.isEmpty()){
            for(Lead l :testLead2){
                l.Company = 'TestAccount1';
                toUpdate.add(l);
            }
        }else {System.debug('No lead with test company');}
        update toUpdate;
        Task testTask = new Task(Description = 'Test', WhoId = testLead3.Id);
        insert testTask;
        merge testLead3 testlead;
        test.stopTest();
        
        // System.assert(toUpdate[0].IsConverted);
        
    }
    @isTest
    public static void taskListTest(){
        createCustomSetting();
        Test.setMock(HttpCalloutMock.class, new EgnyteHttpCalloutImpl());
        Lead testLead = new Lead (FirstName ='t',LastName = 'testLead2', Email='test@example.com',Company = 'test1',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        Lead testLead2 = new Lead (FirstName ='t',LastName = 'testLead2',Email='test@example.com',Company = 'test2',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        List<Task> duplicatedTask = new List<Task>();
        test.startTest();
        insert testLead;
         
        insert testLead2;
        
        Lead testInsert1 = new Lead();
        testInsert1 = [Select id from Lead where id = :testLead.id];
       // System.debug('testLead1 - '+testInsert1);
        
        Lead testInsert2 = new Lead();
        testInsert2 = [Select id from Lead where id = :testLead2.id];
        //System.debug('testLead2 - '+testInsert2);
        
            delete testInsert1;
       test.stopTest();
    }

    @isTest
    public static void autoConvertOnUpdate2(){
        createCustomSetting();
        Test.setMock(HttpCalloutMock.class, new EgnyteHttpCalloutImpl());
        Account testAccount = new Account(Name='TestAccount1',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Lead testlead1 = new Lead(LastName = 'testLead2',Company = 'test1',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        Lead testlead3 = new Lead(LastName = 'testLead1',Company = 'test2',AccountTypeNew__c = 'Unknown',Status='Open',CF_Sub_Lead_Source__c='test',Run_Duplicate_Rules__c=true);
        List<Lead> toUpdate = new List<Lead>();
        test.startTest();
        insert testAccount;
        insert testLead1;
        insert testLead3;
        List<Lead> testLead2 = new List<Lead>([Select id, LastName, Company from Lead where Company ='test' limit 1]);
        if (!testlead2.isEmpty()){
            for(Lead l :testLead2){
                l.Company = 'TestAccount1';
                toUpdate.add(l);
            }
        }else {System.debug('No lead with test company');}
        update toUpdate;
        Task testTask = new Task(Description = testLead3.Id, WhoId = testLead3.Id);
        insert testTask;
        merge testLead3 testlead1;
        test.stopTest();
        
        // System.assert(toUpdate[0].IsConverted);
        
    }

    private static void createCustomSetting() {
        Egnyte__c egnCs = Egnyte__c.getOrgDefaults();
        egnCs.Value__c = '1111111111111111111111';
        upsert egnCs Egnyte__c.Id;
        EgnyteGeneral__c egnCsGent = EgnyteGeneral__c.getOrgDefaults();
        egnCsGent.Value__c = '1111111111111111111111';
        upsert egnCsGent EgnyteGeneral__c.Id;
    }
    
}