src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccTypeNew__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Status__c</fullName>
        <description>The current status of the client.</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CF_Lead_Source__c</fullName>
        <inlineHelpText>The high level way in which this contact was introduced to CleanFund.  CF Sub Lead source captures the specific way we were introduced.</inlineHelpText>
        <label>CF Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CF_Lead_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Can_contact_with_marketing_materials__c</fullName>
        <inlineHelpText>Can CleanFund reach out to this person with marketing collateral?</inlineHelpText>
        <label>Can contact with marketing materials?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>CF Sub-Lead Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/CF_Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor on Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Web Quote Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search (Outbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry (Inbound)</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
        <isActive>false</isActive>
        <label>Website Inquiry</label>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
        <isActive>false</isActive>
        <label>Web Search</label>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
        <isActive>false</isActive>
        <label>UNKNOWN</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
        <isActive>false</isActive>
        <label>Journal</label>
    </customValue>
    <masterLabel>CF Lead Source</masterLabel>
</GlobalValueSet>

src/globalValueSets/GlobalAccType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
        <label>Lender</label>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>City</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>County</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
        <default>true</default>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Third party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>GlobalAccType</masterLabel>
</GlobalValueSet>

src/globalValueSets/Lead_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CleanQuote</fullName>
    </customValue>
    <customValue>
        <fullName>Conference</fullName>
    </customValue>
    <customValue>
        <fullName>Employee Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Account Contacts</fullName>
    </customValue>
    <customValue>
        <fullName>External Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Web Search</fullName>
    </customValue>
    <customValue>
        <fullName>Website Inquiry</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest  {

    @isTest
    public static void testAccTriggerMethods(){
        Account testAccount = new Account(Name='TestAccount1',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Account testAccountMaster = new Account(Name='TestAccount2',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Contact testContact = new Contact(FirstName ='test', LastName='TestContact1', Email = 'test@example.com',CF_Lead_Source__c='Other',Sub_Lead_Source__c='test',Can_contact_with_marketing_materials__c='Yes');
        Contact testContact2 = new Contact(FirstName ='test', LastName='TestContact1',Email = 'test@example.com',CF_Lead_Source__c='Other',Sub_Lead_Source__c='test',Can_contact_with_marketing_materials__c='Yes');
        test.startTest();
        insert new List<Account>{testAccount, testAccountMaster};
        testContact.AccountId = testAccount.id;
        insert testContact;
        testContact2.AccountId = testAccount.id;
        insert testContact2;
        testAccount.Name = 'TestAccount3';
        //testAccount.MasterRecordId = testAccountMaster.Id;
        update testAccount;
        testAccount = [SELECT Id, MasterRecordId FROM Account WHERE Id = :testAccount.Id];
        Task testTask = new Task(WhatId = testAccount.Id, Description = testAccountMaster.Id);
        insert testTask;
        Contact testInsert1 = new Contact();
        testInsert1 = [Select id from Contact where id = :testContact.id];
       // System.debug('testLead1 - '+testInsert1);
        
        Contact testInsert2 = new Contact();
        testInsert2 = [Select id from Contact where id = :testContact2.id];
        //System.debug('testLead2 - '+testInsert2);
        
            delete testInsert1;
        merge testAccountMaster testAccount;
        System.assertEquals(true, [SELECT ID FROM Task].size() > 0, 'There should be tasks');
       test.stopTest();
    }

        @isTest
    public static void testAccTriggerMethods2(){
        Account testAccount = new Account(Name='TestAccount1',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Account testAccountMaster = new Account(Name='TestAccount2',AccTypeNew__c = 'Unknown',Client_Status__c='N/A',CF_Lead_Source__c='Other');
        Contact testContact = new Contact(FirstName ='test', LastName='TestContact1', Email = 'test@example.com',CF_Lead_Source__c='Other',Sub_Lead_Source__c='test',Can_contact_with_marketing_materials__c='Yes');
        Contact testContact2 = new Contact(FirstName ='test', LastName='TestContact1',Email = 'test@example.com',CF_Lead_Source__c='Other',Sub_Lead_Source__c='test',Can_contact_with_marketing_materials__c='Yes');
        test.startTest();
        insert new List<Account>{testAccount, testAccountMaster};
        testContact.AccountId = testAccount.id;
        insert testContact;
        testContact2.AccountId = testAccount.id;
        insert testContact2;
        testAccount.Name = 'TestAccount3';
        //testAccount.MasterRecordId = testAccountMaster.Id;
        update testAccount;
        testAccount = [SELECT Id, MasterRecordId FROM Account WHERE Id = :testAccount.Id];
        Task testTask = new Task(WhatId = testAccount.Id, Description = 'Test');
        insert testTask;
        Contact testInsert1 = new Contact();
        testInsert1 = [Select id from Contact where id = :testContact.id];
       // System.debug('testLead1 - '+testInsert1);
        
        Contact testInsert2 = new Contact();
        testInsert2 = [Select id from Contact where id = :testContact2.id];
        //System.debug('testLead2 - '+testInsert2);
        
            delete testInsert1;
        merge testAccountMaster testAccount;
        System.assertEquals(true, [SELECT ID FROM Task].size() > 0, 'There should be tasks');
       test.stopTest();
    }
}