src/objects/Bond__c.object
<CustomObject>
    <description>This object holds information about the bond.</description>
    <fields>
        <fullName>AC_Count__c</fullName>
        <inlineHelpText>The number of assessment contracts in the bond.</inlineHelpText>
        <label>Number of Assessments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bond</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bond__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Bond</inlineHelpText>
        <label>Bond</label>
        <referenceTo>Bond__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parcel_Count__c</fullName>
        <inlineHelpText>The number of Parcels (APNs) for this opportunity.</inlineHelpText>
        <label>Parcel Count</label>
        <summaryForeignKey>Parcel__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AssesstmentContactCountHandler.cls
/**
12.02.2018 Rodion Vakulovskyi createdTriggerHandler
**/
public class AssesstmentContactCountHandler {
    
	public static void onAfterUpdate(List<Opportunity> inputNewList, Map<Id, Opportunity> inputOldMap) {
        List<Opportunity>  opportunities =  new  List<Opportunity>();
        for(Opportunity opp : inputNewList){
                if((opp.Parcel_Count__c != inputOldMap.get(opp.id).Parcel_Count__c) ||
                (opp.Bond__c != inputOldMap.get(opp.id).Bond__c)){
                    opportunities.add(opp);
                }
        }
        processAfter(opportunities);
    }
    
    public static void onAfterInsert(List<Opportunity> inputNewList) {
        processAfter(inputNewList);
    }
    
    public static void onAfterUndelete(List<Opportunity> inputNewList) {
        processAfter(inputNewList);
    }
    
    public static void onAfterDelete(List<Opportunity> inputOldList) {
        processAfter(inputOldList);
    }
    
    private static void processAfter(List<Opportunity> inputList) {
        List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions1 = new List<RollUpSummaryUtility.fieldDefinition> {
                    															new RollUpSummaryUtility.fieldDefinition('SUM', 'Parcel_Count__c','AC_Count__c')
            																	};
    	RollUpSummaryUtility.ObjectDefination objDef = new RollUpSummaryUtility.ObjectDefination('Opportunity','Bond__c','Bond__c','',null);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions1, objDef , inputList);
    }
}