src/objects/Bond__c.object
<CustomObject>
    <description>This object holds information about the bond.</description>
    <fields>
        <fullName>AC_Count__c</fullName>
        <inlineHelpText>The number of assessment contracts in the bond.</inlineHelpText>
        <label>Number of Assessments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Blended_Coupon__c</fullName>
        <inlineHelpText>This is the calculated blended coupon rate</inlineHelpText>
        <label>Blended Coupon</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Bond_Amount__c</fullName>
        <inlineHelpText>The total amount of the bond (Principal) - a rollup of the underlying assessment contracts.</inlineHelpText>
        <label>Bond Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bond_Cost__c</fullName>
        <inlineHelpText>The total cost of the bond (Payments + Interest) excludes Capitalized Interest and Fees</inlineHelpText>
        <label>Bond Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bond</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bond_Cost__c</fullName>
        <inlineHelpText>Total Bond Cost - Principle+Interest+Fees.  Does not include Capitalized Interest Payments.  (This is this properties contribution to the bond cost, if there is more than one property associated with the bond it will be rolled up at the bond level)</inlineHelpText>
        <label>Bond Cost</label>
        <summarizedField>Parcel__c.Total_Cost_P_I_Fees__c</summarizedField>
        <summaryForeignKey>Parcel__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Bond_Total__c</fullName>
        <inlineHelpText>Roll Up of Bond Principle on all APNs.  This represents this properties contribution to the bond total, if there is more than one property it will be rolled up at the bond level.</inlineHelpText>
        <label>Bond Total</label>
        <summarizedField>Parcel__c.Bond_Total__c</summarizedField>
        <summaryForeignKey>Parcel__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Bond__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Bond</inlineHelpText>
        <label>Bond</label>
        <referenceTo>Bond__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contribution_to_Bond_Rate__c</fullName>
        <formula>Interest_Rate__c*(Bond_Total__c/ Bond__r.Bond_Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If there are more than one properties associated with the bond/assignment this is this properties portion of the blended rate..  The bond blended rate will be rolled up at the bond level.</inlineHelpText>
        <label>Contribution to Bond Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Parcel_Count__c</fullName>
        <inlineHelpText>The number of Parcels (APNs) for this opportunity.</inlineHelpText>
        <label>Parcel Count</label>
        <summaryForeignKey>Parcel__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BondRollupHandler.cls
/**
12.02.2018 Rodion Vakulovskyi createdTriggerHandler
**/
public class BondRollupHandler {
    public static Boolean Flag = true;
	public static void onAfterUpdate(List<Opportunity> inputNewList, Map<Id, Opportunity> inputOldMap) {
        List<Opportunity> opportunities = new List<Opportunity>();
		for(Opportunity opp : inputNewList){
        	if((opp.Bond_Total__c != inputOldMap.get(opp.id).Bond_Total__c)||
            	(opp.Bond__c != inputOldMap.get(opp.id).Bond__c)||
            	(opp.Bond_Cost__c != inputOldMap.get(opp.id).Bond_Cost__c)||
            	(opp.Parcel_Count__c != inputOldMap.get(opp.id).Parcel_Count__c)) {
            	opportunities.add(opp);
            }
        }
        processAfter(opportunities);
    }
    
    public static void onAfterInsert(List<Opportunity> inputNewList) {
     	processAfter(inputNewList);
    }
    
    public static void onAfterUndelete(List<Opportunity> inputNewList) {
       processAfter(inputNewList);
    }
    
    public static void onAfterDelete(List<Opportunity> inputOldList) {
    	processAfter(inputOldList);
    }
    
    private static void processAfter(List<Opportunity> inputList) {
        List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions1 = new List<RollUpSummaryUtility.fieldDefinition> {
																		new RollUpSummaryUtility.fieldDefinition('SUM', 'Bond_Total__c', 'Bond_Amount__c')
            														   };
    	List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions2 = new List<RollUpSummaryUtility.fieldDefinition> {
                    													new RollUpSummaryUtility.fieldDefinition('SUM', 'Contribution_to_Bond_Rate__c', 'Blended_Coupon__c')
            														   };


    	List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions3 = new List<RollUpSummaryUtility.fieldDefinition> {
               															 new RollUpSummaryUtility.fieldDefinition('SUM', 'Bond_Cost__c', 'Bond_Cost__c')
                													   };

    	List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions4 = new List<RollUpSummaryUtility.fieldDefinition> {
            															 new RollUpSummaryUtility.fieldDefinition('SUM', 'Parcel_Count__c', 'AC_Count__c')
        															   };

		RollUpSummaryUtility.ObjectDefination objDef = new RollUpSummaryUtility.ObjectDefination('Opportunity','Bond__c','Bond__c','',null);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions1, objDef , inputList);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions2, objDef , inputList);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions3, objDef , inputList);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions4, objDef , inputList);
    }
}