src/objects/Bond__c.object
<CustomObject>
    <description>This object holds information about the bond.</description>
    <fields>
        <fullName>Bond_Cost__c</fullName>
        <inlineHelpText>The total cost of the bond (Payments + Interest) excludes Capitalized Interest and Fees</inlineHelpText>
        <label>Bond Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bond</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bond_Cost__c</fullName>
        <inlineHelpText>Total Bond Cost - Principle+Interest+Fees.  Does not include Capitalized Interest Payments.  (This is this properties contribution to the bond cost, if there is more than one property associated with the bond it will be rolled up at the bond level)</inlineHelpText>
        <label>Bond Cost</label>
        <summarizedField>Parcel__c.Total_Cost_P_I_Fees__c</summarizedField>
        <summaryForeignKey>Parcel__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Bond__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Bond</inlineHelpText>
        <label>Bond</label>
        <referenceTo>Bond__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BondCostRollupHandler.cls
/**
12.02.2018 Rodion Vakulovskyi createdTriggerHandler
**/
public class BondCostRollupHandler {
	
    public static void onAfterUpdate(List<Opportunity> inputNewList, Map<Id, Opportunity> inputOldMap) {
        List<Opportunity>  opportunities =  new  List<Opportunity>();
     	for(Opportunity opp : inputNewList){
                if((opp.Bond_Cost__c != inputOldMap.get(opp.id).Bond_Cost__c)||
                        (opp.Bond__c != inputOldMap.get(opp.id).Bond__c)) {
                    opportunities.add(opp);
                }
        }
        processAfter(opportunities);
    }
    
    public static void onAfterInsert(List<Opportunity> inputNewList) {
        processAfter(inputNewList);
    }
    
    public static void onAfterUndelete(List<Opportunity> inputNewList) {
        processAfter(inputNewList);
    }
    
    public static void onAfterDelete(List<Opportunity> inputOldList) {
        processAfter(inputOldList);
    }
    
    private static void processAfter(List<Opportunity> inputList) {
        List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions1 = new list<RollUpSummaryUtility.fieldDefinition> {
                    													new RollUpSummaryUtility.fieldDefinition('SUM', 'Bond_Cost__c', 'Bond_Cost__c')
            													  };
   		RollUpSummaryUtility.ObjectDefination objDef = new RollUpSummaryUtility.ObjectDefination('Opportunity','Bond__c','Bond__c','',null);
    	new RollUpSummaryUtility().rollUp(fieldDefinitions1, objDef , inputList);  
    }
}