src/objects/CleanQuoteUser__c.object
<CustomObject>
    <description>The user information for CleanQuote</description>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <inlineHelpText>The Last Name of the User Registered</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CleanQuoteUser</label>
    <nameField>
        <label>CleanQuoteUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CleanQuoteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CleanQuoteUserCntrTest.cls
@isTest
public class CleanQuoteUserCntrTest  {
    public static testmethod void testController(){
        CleanQuoteUser__c testRecord = new CleanQuoteUser__c(Name = 'Test', Last_Name__c = 'Test', Email__c = 'rod@gmail.com');
        insert testRecord;
        PageReference pageRef = Page.CleanQuoteUserConvertion;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(testRecord.Id));
        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(testRecord);
            CleanQuoteUserCntr testContr = new CleanQuoteUserCntr(sc);
            testContr.getObjectPickerList();
            testContr.getFieldsContact();
            testContr.getFieldsAccount();
            testContr.objectPicker = 'accToConvert';
            testContr.convertCQUser();
            testContr.objectPicker = 'contactToConvert';
            testContr.convertCQUser();
        Test.stopTest();
    }
}