src/objects/Egnyte__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Egnyte</label>
</CustomObject>

src/objects/EgnyteGeneral__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Egnyte General</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AccountTypeNew__c</fullName>
        <description>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</description>
        <inlineHelpText>Type of Lead.  IMPORTANT: If you want this to be tracked as a deal, SET THIS AS &quot;OWNER&quot;!</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalAccType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CF_Sub_Lead_Source__c</fullName>
        <description>Name the specific Lead Source.</description>
        <label>CF Sub-Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Possible_matched_Accounts__c</fullName>
        <label>Possible matched Accounts</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Run_Duplicate_Rules__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>An indication whether to run duplication rules or not.</inlineHelpText>
        <label>Run Duplicate Rules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GlobalAccType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
        <label>Lender</label>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>City</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>County</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
        <default>true</default>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>Owner Rep</fullName>
    </customValue>
    <customValue>
        <fullName>PACE Program</fullName>
    </customValue>
    <customValue>
        <fullName>Servicer</fullName>
    </customValue>
    <customValue>
        <fullName>Third party Report Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Transaction Counsel</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>GlobalAccType</masterLabel>
</GlobalValueSet>

src/classes/LeadMatchingControllerTest.cls
@IsTest
private class LeadMatchingControllerTest {

    @IsTest
    public static void constructorTest() {
        Lead testLead = createLead('testLead');
        Test.setCurrentPage(Page.LeadPossibleMatchedAccounts);
        ApexPages.currentPage().getParameters().put('Id', testLead.Id);
        
        Test.startTest();
        LeadMatchingAccountsController controller = new LeadMatchingAccountsController(new ApexPages.StandardController(testLead));
        controller.selectedResult = 'testAccount';
        controller.save();
        Test.stopTest();
    }

    private static Lead makeLead(String name) {
        Lead testLead = new Lead();
        testLead.LastName = name;
        testLead.Company = 'test';
        testLead.AccountTypeNew__c='Unknown';
        testLead.Status='Open';
        testLead.CF_Sub_Lead_Source__c='test';
        testLead.Possible_matched_Accounts__c = 'testAccount;test123;test2222;Test Inc.';
        testLead.Run_Duplicate_Rules__c=true;
        
        return testLead;
    }

    private static Lead createLead(String name) {
        createCustomSetting();
        Lead testLead = makeLead(name);
        insert testLead;
        return testLead;
    }

    private static void createCustomSetting() {
        Egnyte__c egnCs = Egnyte__c.getOrgDefaults();
        egnCs.Value__c = '1111111111111111111111';
        upsert egnCs Egnyte__c.Id;
        EgnyteGeneral__c egnCsGent = EgnyteGeneral__c.getOrgDefaults();
        egnCsGent.Value__c = '1111111111111111111111';
        upsert egnCsGent EgnyteGeneral__c.Id;
    }
  
}