src/objects/Egnyte__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Egnyte</label>
</CustomObject>

src/classes/EgnyteEncryptionClass.cls
public class EgnyteEncryptionClass  {

    public static void cryptPassword(String password) {
        String val = password;
        Blob key = Blob.valueOf('egnytekeyforSFDC');
        Blob encryptedValue = Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(val));
        String encryptedString = EncodingUtil.base64encode(encryptedValue);
        Egnyte__c egnyteCS = Egnyte__c.getOrgDefaults();
        egnyteCS.Value__c = encryptedString;
        upsert egnyteCS;
    }
}