src/objects/Lien__c.object
<CustomObject>
    <description>Describes the outstanding debt on the field.</description>
    <fields>
        <fullName>Debt_Position__c</fullName>
        <inlineHelpText>What is the position of this lender in the loss position?</inlineHelpText>
        <label>Debt Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st</fullName>
                </value>
                <value>
                    <fullName>2nd</fullName>
                </value>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>4th</fullName>
                </value>
                <value>
                    <fullName>5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lender_Acknowledgement__c</fullName>
        <inlineHelpText>Date the Lender has acknowledged that a PACE lien is being place on the property.</inlineHelpText>
        <label>Lender Acknowledgement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The name of the bank or lender.</inlineHelpText>
        <label>Mortgage Lender</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Liens</relationshipLabel>
        <relationshipName>Liens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Liens</relationshipLabel>
        <relationshipName>Opportunity_Liens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lien</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Lien Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lender_Ack_Start_Date__c</fullName>
        <inlineHelpText>The date the lender consent package was sent to the lender.</inlineHelpText>
        <label>Lender Ack. Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lender_Ack_Status__c</fullName>
        <inlineHelpText>This will look at the list of liens and compute the status.   Liens that have the placeholder field will not be considered.
0 - Liens  N/A
No Liens Acknowledged - Not Started
Some Liens Acknowledged - In Progress
All Liens Acknowledged - Completed</inlineHelpText>
        <label>Lender Ack. Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None Received</fullName>
                </value>
                <value>
                    <fullName>Some Received</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Mortgage lender on the transaction (direct or servicer)
Please select &quot;No Lender&quot; in case of no lender. You can find this placeholder account through the lookup field.</description>
        <inlineHelpText>Use the lookup field to the right to select or add a new mortgage lender.</inlineHelpText>
        <label>Mortgage Lender (1st)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lenders__c</fullName>
        <defaultValue>&quot;N/A&quot;</defaultValue>
        <inlineHelpText>This is a semi-colon separated list of lien holder (mortgage lenders, secured debt holders) names.</inlineHelpText>
        <label>Mortgage Lenders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityLienTriggerHandler.cls
public class OpportunityLienTriggerHandler {

    @future
    public static void ProcessLienAsync(Set<ID> opportunityIds){

        // holds a map of the opportunity id and comma separated regions to build
        Map<Id, String> lienLenderMap = new Map<Id, String>();
        Map<Id, String> lienLenderAckMap = new Map<Id, String>();

        // get ALL of the liens for all affected opportunities so we can build
        List<Lien__c> liens = [select id, opportunity__c, Mortgage_Lender__r.Name, Lender_Acknowledgement__c from Lien__c
        	where Opportunity__C IN :opportunityIds order by Debt_Position__c];
        List<AggregateResult> liensCountbyOpp = [Select Opportunity__c, Count(Id), Count(Lender_Acknowledgement__c) From Lien__c 
        	where Opportunity__C IN :opportunityIds Group By Opportunity__c];

        for (Lien__c lien : liens) {
            if (!lienLenderMap.containsKey(lien.Opportunity__C)) {
                // if the key (opportunity) doesn't exist, add it with the lien
                system.debug('Oppurtunity Id1 new lien: ' + lien.Mortgage_Lender__r.Name);
                lienLenderMap.put(lien.Opportunity__C,lien.Mortgage_Lender__r.Name);
            } else {
                // if the key (opportunity) already exist, add ", lien"
                system.debug('Oppurtunity Id2 old lien: ' + lien.Mortgage_Lender__r.Name);
                if (lien.Mortgage_Lender__r.Name != null)
                	lienLenderMap.put(lien.Opportunity__C,lienLenderMap.get(lien.Opportunity__C) +
                        ';' + lien.Mortgage_Lender__r.Name);
            }
        }
 
        for (AggregateResult lienrollup : liensCountbyOpp) {
            Integer numOfLiens = (Integer) lienrollup.get('expr0');
            Integer numOfAcknowledgements = (Integer) lienrollup.get('expr1');
            String oppId = (String) lienrollup.get('Opportunity__c');
            
            if (numOfAcknowledgements == numOfLiens)
                lienLenderAckMap.put(oppId, 'Received');
            else if (numOfAcknowledgements == 0)
                lienLenderAckMap.put(oppId, 'None Received');
            else if (numOfAcknowledgements < numOfLiens)
                lienLenderAckMap.put(oppId, 'Some Received');
            else 
                lienLenderAckMap.put(oppId, 'N/A');
        }


        // get the opportunities that were affected
        List<Opportunity> opportunities = [select id, Lender_Ack_Start_Date__c  from Opportunity where Id IN :opportunityIds];

        // add the comma separated list of regions
        for (Opportunity o : opportunities) {
            o.Mortgage_Lenders__c  = lienLenderMap.get(o.id);
            o.Lender_Ack_Status__c  = lienLenderAckMap.get(o.id);
        }
        update opportunities;

    }

}