src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PACE_Program_New__c</fullName>
        <label>PACE Program</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State_Prop__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AE2</fullName>
                </value>
                <value>
                    <fullName>Anne Arundel County PACE Program</fullName>
                </value>
                <value>
                    <fullName>Better Buildings Northwest Ohio</fullName>
                </value>
                <value>
                    <fullName>CaliforniaFIRST</fullName>
                </value>
                <value>
                    <fullName>CEDA</fullName>
                </value>
                <value>
                    <fullName>CEFIA</fullName>
                </value>
                <value>
                    <fullName>Clean Energy Atlanta</fullName>
                </value>
                <value>
                    <fullName>Clean Energy Chula Vista</fullName>
                </value>
                <value>
                    <fullName>Clean Energy Green Corridor, Miami-Dade</fullName>
                </value>
                <value>
                    <fullName>Clean Energy Sacramento</fullName>
                </value>
                <value>
                    <fullName>Commercial HERO PACE Program</fullName>
                </value>
                <value>
                    <fullName>Commercial PACEDirect</fullName>
                </value>
                <value>
                    <fullName>CO-PACE</fullName>
                </value>
                <value>
                    <fullName>CT-PACE</fullName>
                </value>
                <value>
                    <fullName>DC PACE</fullName>
                </value>
                <value>
                    <fullName>Energize NY</fullName>
                </value>
                <value>
                    <fullName>FigTree</fullName>
                </value>
                <value>
                    <fullName>Florida PACE Funding Agency Program</fullName>
                </value>
                <value>
                    <fullName>Greater Cincinnati Energy Alliance</fullName>
                </value>
                <value>
                    <fullName>Green Energy Works</fullName>
                </value>
                <value>
                    <fullName>GreenFinanceSF</fullName>
                </value>
                <value>
                    <fullName>Howard County PACE Program</fullName>
                </value>
                <value>
                    <fullName>KY PACE</fullName>
                </value>
                <value>
                    <fullName>LA PACE</fullName>
                </value>
                <value>
                    <fullName>LCEID</fullName>
                </value>
                <value>
                    <fullName>Lean and Green Michigan</fullName>
                </value>
                <value>
                    <fullName>Leon County Commercial PACE Program</fullName>
                </value>
                <value>
                    <fullName>MCED</fullName>
                </value>
                <value>
                    <fullName>Milwaukee Energy Efficiency (ME2)</fullName>
                </value>
                <value>
                    <fullName>Minnesota Edina Emerald Energy Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Prop__c</fullName>
        <label>State - Property</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/fetchPicklistOptsControllerCustom.cls
public class fetchPicklistOptsControllerCustom {
    
 	@AuraEnabled
	public static List <String> getselectOptions(String objObject, string fld, String controleObjectValue) {
  		List <String> allOpts = new List <String>();
  		SObjectType customMetaType = Schema.getGlobalDescribe().get(objObject);
  		Schema.DescribeSObjectResult objDescribe = customMetaType.getDescribe();
  		Map <String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        if(fld == 'PACE_Program_New__c' && !String.isEmpty(controleObjectValue)) {
            
            String stateProp;
            if(Test.isRunningTest()) {
                stateProp = 'CA';
            } else {
                Opportunity oppToSearch = [SELECT Id, State_Prop__c FROM Opportunity WHERE Id = :controleObjectValue];
				stateProp = oppToSearch.State_Prop__c;
            }
            if(!String.isEmpty(stateProp)){
            	Map<Object,List<String>> mapOfValues = getDependentPicklistValues('Opportunity', 'PACE_Program_New__c');
                System.debug(mapOfValues.get(stateProp));
                System.debug(mapOfValues);
            	for(String itemString : mapOfValues.get(stateProp)) {
                	allOpts.add(itemString);
            	}
            }
        } else {
            List <Schema.PicklistEntry > values = fieldMap.get(fld).getDescribe().getPickListValues();
  			for (Schema.PicklistEntry a: values) {
   				allOpts.add(a.getValue());
  			}
        }
  		allOpts.sort();
  		return allOpts;
 	}
    
public static Map<Object,List<String>> getDependentPicklistValues( Schema.sObjectField dependToken )
{
    Schema.DescribeFieldResult depend = dependToken.getDescribe();
    Schema.sObjectField controlToken = depend.getController();
    if ( controlToken == null ) return null;
    Schema.DescribeFieldResult control = controlToken.getDescribe();
    List<Schema.PicklistEntry> controlEntries =
    (   control.getType() == Schema.DisplayType.Boolean
    ?   null
    :   control.getPicklistValues()
    );
 
    String base64map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    Map<Object,List<String>> dependentPicklistValues = new Map<Object,List<String>>();
    for (Schema.PicklistEntry entry : depend.getPicklistValues() ) if ( entry.isActive() ) {
        List<String> base64chars = String.valueOf(((Map<String, Object>) JSON.deserializeUntyped( JSON.serialize( entry ) )).get( 'validFor' )).split( '' );
        for ( Integer index = 0; index < (controlEntries != null ? controlEntries.size() : 2); index++ ){
            Object controlValue =
            (   controlEntries == null
            ?   (Object) (index == 1)
            :   (Object) (controlEntries[ index ].isActive() ? controlEntries[ index ].getLabel() : null)
            );
            Integer bitIndex = index / 6, bitShift = 5 - Math.mod( index, 6 );
            System.debug(base64chars);
            if  (   controlValue == null
                ||  ((base64chars.size() > bitIndex) && (base64map.indexOf( base64chars[ bitIndex ] ) & (1 << bitShift)) == 0
                )) continue;
            if ( !dependentPicklistValues.containsKey( controlValue ) ){
                dependentPicklistValues.put( controlValue, new List<String>() );
            }
            dependentPicklistValues.get( controlValue ).add( entry.getLabel() );
        }
    }
    return dependentPicklistValues;
}
    
    public static Map<Object,List<String>> getDependentPicklistValues(String sObjectName, String fieldName){
    	return getDependentPicklistValues(Schema.getGlobalDescribe().get(sObjectName).getDescribe().fields.getMap().get(fieldName));
	}
}