src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Prepayment__c</fullName>
        <label>Prepayment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5% (10), 4% (11), 3% (12), 2% (13), 1% (14)</fullName>
                </value>
                <value>
                    <fullName>5% (7), 4% (8), 3% (9), 2% (10), 1% (11)</fullName>
                </value>
                <value>
                    <fullName>4% (7), 3% (8), 2% (9), 1% (10)</fullName>
                </value>
                <value>
                    <fullName>5% (5), 4% (6), 3% (7), 2% (8), 1% (9)</fullName>
                </value>
                <value>
                    <fullName>4% (5), 3% (6), 2% (7), 1% (8)</fullName>
                </value>
                <value>
                    <fullName>3% (8), 2% (9), 1% (10)</fullName>
                </value>
                <value>
                    <fullName>Yield Maintenance (special)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Prepayment_Step__c.object
<CustomObject>
    <description>Prepayement steps, including all relevant data.</description>
    <fields>
        <fullName>Prepayment_Step__c</fullName>
        <description>The Step</description>
        <inlineHelpText>The Step</inlineHelpText>
        <label>Prepayment Step</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prepayment Step</label>
    <nameField>
        <label>Prepayment Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prepayment Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PrepaymentStepCreationTrgHandlerTest.cls
@isTest
public class PrepaymentStepCreationTrgHandlerTest {
    private static testmethod void testPaymentStepInsert() {
        Test.startTest();
        	Opportunity opportunityToInsert = createDataForTest();
        	List<Prepayment_Step__c> listOfPrepayments = new List<Prepayment_Step__c>([SELECT Id FROM Prepayment_Step__c]);
        	System.assertEquals(5, listOfPrepayments.size(), 'List of records should have size 5 and it is : ' +listOfPrepayments.size());
        Test.stopTest();
    }
    
     private static testmethod void testPaymentStepUpdate() {
        Test.startTest();
        	Opportunity opportunityToInsert = createDataForTest();
         	opportunityToInsert.Prepayment__c = '3% (8), 2% (9), 1% (10)';
         	update opportunityToInsert;
        	List<Prepayment_Step__c> listOfPrepayments = new List<Prepayment_Step__c>([SELECT Id FROM Prepayment_Step__c]);
        	System.assertEquals(3, listOfPrepayments.size(), 'List of records should have size 3 and it is : ' +listOfPrepayments.size());
        Test.stopTest();
    }
	private static Opportunity createDataForTest() {
       Account acc = TestHelperUtility.createAccount(null, null, 'TestAccounts', 'Pre-Contact', 'Channel Partner'); 
       insert acc;
       List<Contact> contacts = new list<Contact>();
       // Create two contacts
       Contact ct1 = TestHelperUtility.createContact(acc.Id, 'Larrys', 'Page');
       contacts.add(ct1);
       insert contacts;
       Opportunity opportunityToInsert = TestHelperUtility.createOpportunityForBonds(acc.Id, contacts[0].Id, null, 'Opportunity Contact Insertion Test', 7.5);
       opportunityToInsert.Prepayment__c = '5% (5), 4% (6), 3% (7), 2% (8), 1% (9)';
       insert opportunityToInsert;
    return opportunityToInsert;
    }
}