src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>Estimated loan term (not final)</description>
        <inlineHelpText>Desired length of financing term, expressed in years</inlineHelpText>
        <label>Financing Term</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prepayment__c</fullName>
        <label>Prepayment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5% (10), 4% (11), 3% (12), 2% (13), 1% (14)</fullName>
                </value>
                <value>
                    <fullName>5% (7), 4% (8), 3% (9), 2% (10), 1% (11)</fullName>
                </value>
                <value>
                    <fullName>4% (7), 3% (8), 2% (9), 1% (10)</fullName>
                </value>
                <value>
                    <fullName>5% (5), 4% (6), 3% (7), 2% (8), 1% (9)</fullName>
                </value>
                <value>
                    <fullName>4% (5), 3% (6), 2% (7), 1% (8)</fullName>
                </value>
                <value>
                    <fullName>3% (8), 2% (9), 1% (10)</fullName>
                </value>
                <value>
                    <fullName>Yield Maintenance (special)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Prepayment_Step__c.object
<CustomObject>
    <description>Prepayement steps, including all relevant data.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Related Opportunity</description>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prepayment Steps</relationshipLabel>
        <relationshipName>Prepayment_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prepayment_Penalty__c</fullName>
        <description>Penalty for prepayment at this step (%).</description>
        <label>Prepayment Penalty</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prepayment_Step_Year_End__c</fullName>
        <description>The year in which this prepayment step ends.  YYYY Format required.</description>
        <inlineHelpText>The year in which this prepayment step ends.  YYYY Format.</inlineHelpText>
        <label>Prepayment Step Year End</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prepayment_Step__c</fullName>
        <description>The Step</description>
        <inlineHelpText>The Step</inlineHelpText>
        <label>Prepayment Step</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yield_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Yield Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <label>Prepayment Step</label>
    <nameField>
        <label>Prepayment Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prepayment Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PrepaymentStepCreationTrgHandler.cls
public class PrepaymentStepCreationTrgHandler {
    
    public static void onAfterInsert(List<Opportunity> inputList) {
        List<Opportunity> listToOperate = new List<Opportunity>();
        for(Opportunity itemOpp : inputList) {
            if(!String.isEmpty(itemOpp.Prepayment__c)) {
               listToOperate.add(itemOpp);
            }
        }
        if(listToOperate.size() > 0) {
           processCreation(inputList); 
        }
    }
    
    public static void onAfterUpdate(List<Opportunity> inputList, Map<Id, Opportunity> oldMap) {
        List<Opportunity> listToOperate = new List<Opportunity>();
        for(Opportunity itemOpp : inputList) {
            if(itemOpp.Prepayment__c != oldMap.get(itemOpp.Id).Prepayment__c) {
            	listToOperate.add(itemOpp);
            }
        }
        if(listToOperate.size() > 0) {
           processCreation(inputList); 
        }
    }
    
    private static void processCreation(List<Opportunity> inputList) {
		Set<Id> setOfIds = new Set<Id>();
        List<Prepayment_Step__c> listToInsert = new List<Prepayment_Step__c>();
        for(Opportunity oppItem : inputList) {
            setOfIds.add(oppItem.Id);
            if(oppItem.Prepayment__c != 'Yield Maintenance (special)'){
            	List<String> listOfPicklistValues = oppItem.Prepayment__c.split(',');
            	for(Integer i = 0; i < listOfPicklistValues.size(); i ++) {
                	String itemPrep = listOfPicklistValues[i];
                    Prepayment_Step__c prepItemFormed = new Prepayment_Step__c();
                    if(i == listOfPicklistValues.size() -1) {
                        Decimal yearEnd = (oppItem.Loan_Term__c != null) ? oppItem.Loan_Term__c : 20;
                        prepItemFormed = formPrepaymentStep(yearEnd, itemPrep.substring(0,itemPrep.lastIndexOf('%')), i + 1, oppItem.Id);
                    } else {
                        prepItemFormed = formPrepaymentStep(itemPrep.substring(itemPrep.indexOf('(') + 1,itemPrep.indexOf(')')), itemPrep.substring(0,itemPrep.lastIndexOf('%')), i + 1, oppItem.Id);     
                    }
                	listToInsert.add(prepItemFormed);
            	}
            } else {
                listToInsert.add(new Prepayment_Step__c(Opportunity__c = oppItem.Id, Prepayment_Penalty__c = 0, Prepayment_Step_Year_End__c = 0, Prepayment_Step__c  = '1', Yield_Maintenance__c = true));
            }
        } 
        processDelete(setOfIds);
        if(listToInsert.size() >0) {
            insert listToInsert;
        }
    }
    
    private static Prepayment_Step__c formPrepaymentStep(Object inputYearEnd, Object inputPenalty, Integer inputStep, Id inputOppId) {
        Prepayment_Step__c stepToInsert = new Prepayment_Step__c(
            													Prepayment_Penalty__c = Double.valueOf(inputPenalty),
            													Prepayment_Step__c = String.valueOf(inputStep),
            													Prepayment_Step_Year_End__c = Integer.valueOf(inputYearEnd),
            													Opportunity__c = inputOppId
        														);
    return stepToInsert;
    }
    
    private static void processDelete(Set<Id> inputSet) {
        List<Prepayment_Step__c> listToDelete = new List<Prepayment_Step__c>([SELECT Id FROM Prepayment_Step__c WHERE Opportunity__c IN : inputSet]);
        if(listToDelete.size() > 0) {
            delete listToDelete;
        }
    }

}