src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Est_Improvement_Cost__c</fullName>
        <description>Estimate of improvement cost, gross of financing and program fees</description>
        <inlineHelpText>Estimated cost of all improvements.</inlineHelpText>
        <label>C-PACE Project Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>Estimated loan term (not final)</description>
        <inlineHelpText>Desired length of financing term, expressed in years</inlineHelpText>
        <label>Financing Term</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>What is the scope of the project?</description>
        <label>Project Scope</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Construction</fullName>
                </value>
                <value>
                    <fullName>Upgrade/Retrofit</fullName>
                </value>
                <value>
                    <fullName>Gut Rehab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tenant__c.object
<CustomObject>
    <description>This is to capture tenant information.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Opportunity_Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TenantBySqFtSortOder__c</fullName>
        <inlineHelpText>This is updated via a trigger and maintains the sort order of the Tenants in an opportunity.</inlineHelpText>
        <label>TenantBySqFtSortOder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tenant_Square_Foot__c</fullName>
        <label>Tenant Square Foot</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/updateTenantSortOrderHandlerTest.cls
@isTest
private class updateTenantSortOrderHandlerTest {

    private static testMethod void testInsertRecords() {

        List<Opportunity> opportunities = new List<Opportunity>();
        List<Tenant__c> tenants = new List<Tenant__c>();

        // insert some opportunities
        Opportunity o1 = new Opportunity(name='Opportunity 1',StageName='Pre-Qualified Lead', Project_Type__c='TBD',CloseDate=Date.today()+2,
                Est_Improvement_Cost__c = 50.00, Loan_Term__c = 24);
        Opportunity o2 = new Opportunity(name='Opportunity 2', StageName='Pre-Qualified Lead', Project_Type__c='TBD',CloseDate=Date.today()+2,
                Est_Improvement_Cost__c = 50.00, Loan_Term__c = 24);
        opportunities.add(o1);
        opportunities.add(o2);
        insert opportunities;

        Test.startTest();

        tenants.add(new Tenant__c(Opportunity__c=o1.Id, Name='Shop1', Tenant_Square_Foot__c=100));
        tenants.add(new Tenant__c(Opportunity__c=o1.Id, Name='Shop2', Tenant_Square_Foot__c=200));
        tenants.add(new Tenant__c(Opportunity__c=o2.Id, Name='Shop3', Tenant_Square_Foot__c=300));
        tenants.add(new Tenant__c(Opportunity__c=o2.Id, Name='Shop4', Tenant_Square_Foot__c=400));

        insert tenants;

        Test.stopTest();
        
        List<Tenant__c> tenantsRefreshed = 
      		[select id,Name,TenantBySqFtSortOder__c,Tenant_Square_Foot__c from Tenant__c where id IN :tenants];
 
        for (Tenant__c t : tenantsRefreshed) {
            if(t.Name.equals('Shop1'))
                System.assertEquals(2,t.TenantBySqFtSortOder__c);
            if(t.Name.equals('Shop2'))
                System.assertEquals(1,t.TenantBySqFtSortOder__c);
            if(t.Name.equals('Shop3'))
                System.assertEquals(2,t.TenantBySqFtSortOder__c);
            if(t.Name.equals('Shop4'))
                System.assertEquals(1,t.TenantBySqFtSortOder__c);
        }
       }

    private static testMethod void testDeleteRecords() {

        List<Opportunity> opportunities = new List<Opportunity>();
        List<Tenant__c> tenants = new List<Tenant__c>();

        // insert an opportunities

        Opportunity o1 = new Opportunity(name='Opportunity 1',StageName='Pre-Qualified Lead', Project_Type__c='TBD',CloseDate=Date.today()+2,
                Est_Improvement_Cost__c = 50.00, Loan_Term__c = 24);
        opportunities.add(o1);
        insert opportunities;

        tenants.add(new Tenant__c(Opportunity__c=o1.Id, Name='ShopDelete1', Tenant_Square_Foot__c=100));
        tenants.add(new Tenant__c(Opportunity__c=o1.Id, Name='ShopDelete2', Tenant_Square_Foot__c=200));
        
        insert tenants;
        
        Test.startTest();
        // now delete a record and reset recurrsion flag
        TriggerContextUtility.setFirstRunTrue();
        delete tenants.get(1);
        Test.stopTest();
        
        List<Tenant__c> tenantsRefreshed = 
      		[select id,Name,TenantBySqFtSortOder__c,Tenant_Square_Foot__c from Tenant__c where Opportunity__c=:o1.id];
 
        for (Tenant__c t : tenantsRefreshed) {
            if(t.Name.equals('ShopDelete1'))
                System.assertEquals(1,t.TenantBySqFtSortOder__c);
        }
    }

}