src/objects/Tenant__c.object
<CustomObject>
    <description>This is to capture tenant information.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tenants</relationshipLabel>
        <relationshipName>Opportunity_Tenants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TenantBySqFtSortOder__c</fullName>
        <inlineHelpText>This is updated via a trigger and maintains the sort order of the Tenants in an opportunity.</inlineHelpText>
        <label>TenantBySqFtSortOder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tenant_Square_Foot__c</fullName>
        <label>Tenant Square Foot</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/updateTenantSortOrderHandler.cls
public class updateTenantSortOrderHandler {

    public static void processUpdate (Set<ID> opportunityIds){
        Integer order=1;
        List<Tenant__c> tenantsToUpdate;
        for(Id oppid : opportunityIds){
            List<Tenant__c> tenants = 
      		[select id,Name,TenantBySqFtSortOder__c,Tenant_Square_Foot__c from Tenant__c where Opportunity__c =: oppid order by Tenant_Square_Foot__c DESC LIMIT 10];
    		for (Tenant__c t : tenants) {
            	t.TenantBySqFtSortOder__c =order++;
                }
            update tenants;
            order=1;
        }
    }
}